import { e } from "../lib.mjs";

export default [
  e({
    id: "explicit-direct-instruction", label: "Explicit instruction (principles of instruction)", layer: "method",
    aliases: ["direct instruction", "Rosenshine's principles", "explicit teaching"],
    summary: "Present new material in small steps with modelling, guided practice, high-frequency questioning, checks for understanding, and independent practice.",
    mechanism: "Small steps and frequent checks keep working-memory demand manageable and surface errors before they are practised, while modelling makes expert processes visible.",
    traditions: ["cognitive", "behavioral", "instructional-design"], domains: ["general", "literacy", "mathematics"], stages: ["primary", "middle", "secondary", "adult-workplace"],
    functions: ["explain", "practice", "feedback"], grain: "lesson", maturity: "established",
    tasks: ["new skill acquisition", "well-structured procedures", "foundational knowledge"],
    contexts: ["classroom", "intervention", "tutoring", "training"],
    prereq: ["A decomposable skill or body of knowledge", "Prepared examples and checking questions", "Time for guided then independent practice"],
    constraints: ["Explicit is not lecture: it requires high-frequency response and checking", "Guidance must fade as competence grows", "Weakest fit for open, ill-structured, or judgment-laden tasks"],
    risks: ["Degenerating into uninterrupted teacher talk", "Holding guidance constant past the point of expertise reversal", "Over-fitting to the taught examples with no varied practice"],
    obs: [["Independent accuracy on untaught items", "Check-for-understanding hit rate during the lesson plus unassisted delayed items", "Within lesson and after a delay", "High choral response can mask individual non-understanding"]],
    ev: { status: "strong", confidence: "high", basis: "Synthesis of process-product research, cognitive-science findings, and expert-teacher studies converging on the same set of practices; strongest for foundational and well-structured content.", directness: "mixed-direct-and-inferential", generalizability: "Broad for well-structured content and novice learners; weaker evidence for open-ended disciplinary work.", sources: ["rosenshine-principles", "kirschner-minimal-guidance", "ies-study"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Sound default for novel well-structured content, provided checking is frequent and guidance fades." },
    tags: ["method", "novice", "practice", "explanation"],
  }),
  e({
    id: "mastery-learning", label: "Mastery learning", layer: "method",
    aliases: ["Bloom's mastery learning", "learning for mastery", "competency-based progression"],
    summary: "Hold the criterion constant and let time vary: learners receive formative checks, corrective instruction, and re-assessment until a defined standard is met before moving on.",
    mechanism: "Frequent criterion checks plus targeted correctives prevent unremediated gaps from compounding into later failure.",
    traditions: ["behavioral", "instructional-design"], domains: ["general", "mathematics", "professional-workplace"], stages: ["primary", "middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["sequence", "feedback", "assess"], grain: "unit-course", maturity: "established",
    tasks: ["hierarchical skill sequences", "certification", "prerequisite-heavy content"],
    contexts: ["classroom", "adaptive software", "competency-based programs", "clinical training"],
    prereq: ["A defensible mastery criterion", "Genuinely different corrective instruction, not just repetition", "Flexible time and alternative assessment forms"],
    constraints: ["Requires slack time, which fixed-pace systems rarely have", "Effects shrink when correctives are only re-presentation", "Criterion setting is a validity judgment, not a technical default"],
    risks: ["Endless re-testing that becomes attrition by another name", "Gaming the criterion with near-identical retest items", "Fragmenting a subject into checkbox micro-objectives"],
    obs: [["Criterion attainment with transfer retained", "Mastery rate, attempts to mastery, and delayed transfer performance", "Per unit and cumulatively", "Rising mastery rates can reflect easier retests"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analytic evidence of positive average effects, with strong dependence on corrective quality, criterion setting, and implementation.", directness: "direct-intervention", generalizability: "Strongest in hierarchical domains and in mastery-based professional training.", effect: { metric: "d", value: 0.5, note: "Meta-analytic averages vary widely by implementation; treat as a range, not a constant." }, sources: ["kulik-mastery", "mcgaghie-simulation", "bloom-two-sigma"] },
    rec: { status: "contextual-option", rationale: "Strong fit for prerequisite-heavy content when correctives genuinely differ and the criterion is defensible." },
    tags: ["method", "sequence", "assessment", "adaptive"],
  }),
  e({
    id: "one-to-one-tutoring", label: "One-to-one and small-group tutoring", layer: "method",
    aliases: ["high-dosage tutoring", "individual tutoring"],
    summary: "Sustained tutoring by a trained tutor with a small ratio, aligned to the curriculum and scheduled during the day, is among the best-evidenced interventions available.",
    mechanism: "A tutor can diagnose the specific gap, adapt within seconds, keep the learner responding continuously, and sustain a relationship that supports effort.",
    traditions: ["cognitive", "sociocultural"], domains: ["general", "literacy", "mathematics"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["diagnose", "practice", "feedback", "climate"], grain: "program-system", maturity: "established",
    tasks: ["gap remediation", "foundational skills", "accelerated support"],
    contexts: ["one-to-one", "small group", "school day", "intervention"],
    prereq: ["Trained tutors with materials", "Curriculum alignment", "Consistent scheduling and attendance"],
    constraints: ["Effects depend heavily on dosage, ratio, tutor training, and alignment", "Volunteer, low-dosage, or after-school models perform substantially worse", "It is expensive and staffing-constrained"],
    risks: ["Claiming programme-level effects from a thin implementation", "Displacing core instruction rather than supplementing it", "Assuming the classic two-sigma figure is a reproducible benchmark"],
    obs: [["Accelerated growth relative to a comparison group", "Curriculum-aligned progress monitoring plus an independent outcome measure", "Every few weeks and at programme end", "Tutor-administered measures can be optimistic"]],
    ev: { status: "strong", confidence: "high", basis: "Long-standing meta-analytic evidence for tutoring effects, with modern syntheses showing strong dependence on dosage and delivery model.", directness: "direct-intervention", generalizability: "Consistently positive across ages and subjects when implementation conditions are met.", effect: { metric: "d", value: 0.4, note: "Typical modern high-dosage estimates cluster around 0.2-0.6; the historical two-sigma claim is not a reproducible benchmark." }, sources: ["cohen-tutoring-meta", "bloom-two-sigma", "vanlehn-tutoring"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Best-evidenced intensive support model; specify dosage, ratio, training, and alignment before claiming its effects." },
    tags: ["method", "intervention", "adaptive", "equity"],
  }),
  e({
    id: "intelligent-tutoring-systems", label: "Intelligent tutoring systems", layer: "method",
    aliases: ["ITS", "step-based tutoring", "cognitive tutors"],
    summary: "Software that tracks a learner model at step granularity and gives step-level guidance performs close to human tutoring and well above untutored practice.",
    mechanism: "Step-level feedback and hints operate at the granularity where the learner's error actually occurs, giving frequent interaction opportunities that answer-level systems miss.",
    traditions: ["cognitive", "instructional-design"], domains: ["mathematics", "computing", "science", "digital-environments"], stages: ["middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["practice", "feedback", "diagnose"], grain: "unit-course", maturity: "established",
    tasks: ["procedural skill practice", "problem solving with steps", "self-paced remediation"],
    contexts: ["adaptive software", "classroom", "homework systems"],
    prereq: ["A domain decomposable into steps and knowledge components", "A learner model and validated hint content", "Classroom integration and teacher use of the data"],
    constraints: ["Effects are strongest in well-structured domains", "Interaction granularity matters more than the underlying AI technique", "Implementation and teacher use explain much of the variance"],
    risks: ["Optimizing for in-session correctness rather than delayed learning", "Hint abuse and gaming the system", "Assuming a chat interface delivers step-level tutoring without a learner model"],
    obs: [["Learning relative to conventional practice", "Randomized or matched comparison on delayed independent assessment, plus hint-use and gaming detectors", "Across a unit", "In-system mastery flags routinely overstate durable learning"]],
    ev: { status: "strong", confidence: "high", basis: "Convergent meta-analyses find ITS substantially better than no tutoring and roughly comparable to human tutoring, with step granularity as the key moderator.", directness: "direct-intervention", generalizability: "Well-structured domains, mostly mathematics, physics, and programming.", effect: { metric: "g", value: 0.66, note: "Meta-analytic estimates versus conventional instruction commonly fall between 0.4 and 0.8." }, sources: ["vanlehn-tutoring", "kulik-fletcher-its", "ma-its-meta"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "The most directly relevant precedent for an agentic tutoring runtime; the evidence is about step-level interaction, not about the technology label." },
    tags: ["method", "adaptive", "digital", "feedback"],
  }),
  e({
    id: "peer-tutoring", label: "Peer and cross-age tutoring", layer: "method",
    aliases: ["peer-assisted learning", "cross-age tutoring", "dyadic peer practice"],
    summary: "Structured peer tutoring with defined roles, materials, and turn-taking benefits both tutee and tutor at low marginal cost.",
    mechanism: "Tutees get more response opportunities and immediate correction; tutors consolidate through explanation and monitoring.",
    traditions: ["sociocultural", "behavioral"], domains: ["literacy", "mathematics", "general"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["practice", "feedback", "collaborate"], grain: "lesson", maturity: "established",
    tasks: ["fluency practice", "procedural rehearsal", "review"],
    contexts: ["classroom", "small group", "peer explanation"],
    prereq: ["Explicit role training and scripts", "Correct answer keys or scaffolds", "Teacher monitoring"],
    constraints: ["Unstructured pairing produces little", "Tutor must have adequate content accuracy", "Status differences can undermine the weaker partner"],
    risks: ["Reinforcing errors when tutors are wrong", "Exploiting stronger peers as unpaid teachers", "Social exposure of struggling learners"],
    obs: [["Gains for both roles", "Pre-post on target skill for tutor and tutee, plus fidelity checks on the protocol", "Across several weeks", "Protocol drift after the first weeks is common"]],
    ev: { status: "strong", confidence: "moderate", basis: "Classic meta-analytic evidence for structured tutoring programmes, with structure and training as key moderators.", directness: "direct-intervention", generalizability: "Well evidenced for well-defined skills; weaker for open-ended work.", sources: ["cohen-tutoring-meta", "johnson-cooperative"] },
    rec: { status: "contextual-option", rationale: "Use where the target skill has checkable answers and the protocol can be trained and monitored." },
    tags: ["method", "collaboration", "practice", "equity"],
  }),
  e({
    id: "reciprocal-teaching", label: "Reciprocal teaching", layer: "method",
    aliases: ["predicting, questioning, clarifying, summarizing"],
    summary: "Comprehension strategies are taught through structured dialogue in which learners progressively take over the teacher's role in predicting, questioning, clarifying, and summarizing.",
    mechanism: "Strategy use is modelled and then transferred through guided dialogue, so the comprehension monitoring becomes internal rather than teacher-supplied.",
    traditions: ["sociocultural", "cognitive"], domains: ["literacy"], stages: ["primary", "middle", "secondary"],
    functions: ["explain", "collaborate", "self-regulate"], grain: "unit-course", maturity: "established",
    tasks: ["reading comprehension", "text monitoring", "content-area reading"],
    contexts: ["classroom", "small group", "intervention"],
    prereq: ["Adequate decoding for the text", "Explicit modelling before role transfer", "Texts worth discussing"],
    constraints: ["Requires extended sessions, not a single lesson", "Effects are larger on experimenter-designed than on standardized measures", "Strategy overload can displace content learning"],
    risks: ["Turning the four strategies into a ritual", "Using it with texts learners cannot decode", "Assuming standardized-test gains from short implementations"],
    obs: [["Independent comprehension monitoring", "Unfamiliar-text comprehension plus observed strategy use without prompting", "After several weeks and at delay", "Strategy naming is not strategy use"]],
    ev: { status: "strong", confidence: "moderate", basis: "Original controlled studies plus meta-analysis showing consistent benefits, with much larger effects on experimenter-developed than standardized measures.", directness: "direct-intervention", generalizability: "Best evidenced for learners with adequate decoding but weak comprehension.", effect: { metric: "d", value: 0.32, note: "Standardized-measure estimate is markedly smaller than experimenter-measure estimates." }, sources: ["palincsar-brown", "rosenshine-reciprocal", "reading-comprehension-wwc"] },
    rec: { status: "contextual-option", rationale: "Strong option for comprehension when decoding is adequate; expect smaller effects on standardized outcomes." },
    tags: ["method", "literacy", "comprehension", "collaboration"],
  }),
  e({
    id: "cooperative-structures", label: "Structured cooperative learning designs", layer: "method",
    aliases: ["jigsaw", "positive interdependence", "STAD", "team-based learning"],
    summary: "Cooperative designs that build positive interdependence and individual accountability outperform competitive and individualistic structures on achievement and relationships.",
    mechanism: "Interdependence makes each member's contribution necessary while individual accountability prevents free-riding, so explanation and coordination actually occur.",
    traditions: ["sociocultural", "motivational-social"], domains: ["general", "science", "mathematics"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["collaborate", "practice", "climate"], grain: "lesson", maturity: "established",
    tasks: ["group problem solving", "concept discussion", "project division"],
    contexts: ["classroom", "small group", "laboratory"],
    prereq: ["A task that genuinely needs multiple contributors", "Individual accountability mechanism", "Explicit cooperative skills instruction"],
    constraints: ["Group work without interdependence and accountability is not cooperative learning", "Status and language differences shape who participates", "Group products conceal individual understanding"],
    risks: ["Free-riding and status-based exclusion", "Grading the group and inferring individual mastery", "Assuming collaboration suits every task"],
    obs: [["Equitable participation with individual learning", "Individual post-tests plus participation and talk-time distribution", "During and after the unit", "A polished group product can hide non-participation"]],
    ev: { status: "strong", confidence: "high", basis: "Large meta-analytic literature across ages showing cooperative structures outperform competitive and individualistic ones when the defining conditions are present.", directness: "direct-intervention", generalizability: "Robust across ages and subjects when interdependence and accountability are implemented.", effect: { metric: "d", value: 0.5, note: "Adolescent achievement estimates around 0.46; STEM small-group estimates around 0.5." }, sources: ["johnson-cooperative", "roseth-cooperative", "springer-small-group", "collaboration-meta"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Use when the task needs multiple contributors; enforce interdependence, accountability, and individual assessment." },
    tags: ["method", "collaboration", "equity", "accountability"],
  }),
  e({
    id: "active-learning-stem", label: "Active learning in postsecondary STEM", layer: "method",
    aliases: ["clicker questions", "peer instruction", "interactive engagement"],
    summary: "Replacing continuous lecture with structured student activity raises exam performance and cuts failure rates in undergraduate STEM courses, with larger relative gains for underrepresented students.",
    mechanism: "Frequent required responses surface misconceptions during class, provide retrieval and feedback, and shift processing to the learner.",
    traditions: ["cognitive", "instructional-design"], domains: ["science", "mathematics", "engineering-design", "computing"], stages: ["postsecondary"],
    functions: ["practice", "feedback", "collaborate"], grain: "lesson", maturity: "established",
    tasks: ["concept mastery", "problem solving", "large-lecture instruction"],
    contexts: ["higher education", "large lecture", "laboratory"],
    prereq: ["Prepared conceptual questions or tasks", "A response mechanism for every student", "Instructor willingness to adapt on the spot"],
    constraints: ["'Active' covers a wide range of designs of very different quality", "Publication bias likely inflates the average", "Learners often report learning less while learning more"],
    risks: ["Labelling any group activity as active learning", "Abandoning the method because students rate it lower", "Reducing it to unstructured discussion"],
    obs: [["Exam and concept-inventory performance and failure rate", "Common exams or validated concept inventories plus DFW rates, disaggregated by subgroup", "Across a term", "Student satisfaction can move opposite to learning"]],
    ev: { status: "strong", confidence: "high", basis: "Large meta-analyses of controlled comparisons in undergraduate STEM, plus a direct experiment showing perceived learning diverges from measured learning.", directness: "direct-intervention", generalizability: "Undergraduate STEM in particular; the label covers heterogeneous designs.", effect: { metric: "d", value: 0.47, note: "Examination performance; failure rates about 1.5 times higher under lecturing. Achievement-gap reductions of roughly a third reported for underrepresented students." }, sources: ["freeman-active-learning", "theobald-active-equity", "deslauriers-feeling"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Well-evidenced for undergraduate STEM; expect and pre-empt the perceived-learning dip." },
    tags: ["method", "engagement", "equity", "practice"],
  }),
  e({
    id: "problem-based-learning", label: "Problem-based learning", layer: "method",
    aliases: ["PBL", "case-based curriculum"],
    summary: "Learning is organized around authentic ill-structured problems tackled in facilitated groups before or instead of formal exposition.",
    mechanism: "Working a problem first creates a need for knowledge and situates it with its conditions of use; the facilitator supplies process guidance rather than answers.",
    traditions: ["constructivist", "sociocultural"], domains: ["health", "professional-workplace", "science", "engineering-design"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["transfer", "collaborate", "motivate"], grain: "unit-course", maturity: "disputed",
    tasks: ["applying knowledge to cases", "clinical reasoning", "ill-structured problems"],
    contexts: ["professional education", "higher education", "small group"],
    prereq: ["Sufficient prior knowledge to engage the problem", "Trained facilitators", "Explicit consolidation after the problem"],
    constraints: ["Outcome type decides the result: skill application favours PBL, knowledge coverage often favours conventional instruction", "Facilitation quality dominates outcomes", "Minimal-guidance versions are contested on cognitive-load grounds"],
    risks: ["Leaving novices to flounder without guidance", "Skipping consolidation so misconceptions persist", "Assuming enjoyment implies learning"],
    obs: [["Application skill versus knowledge coverage", "Separate measures for knowledge and for application, plus consolidation checks", "End of unit and later", "A single composite outcome hides the pattern"]],
    ev: { status: "contested", confidence: "moderate", basis: "Meta-analyses find advantages for skill application and near-zero or negative effects for knowledge outcomes; the guidance debate remains active.", directness: "direct-intervention", generalizability: "Best evidenced in medical and professional education with strong facilitation.", effect: { metric: "d", note: "Positive for application of knowledge; approximately zero to slightly negative for knowledge acquisition." }, sources: ["dochy-pbl-meta", "hmelo-silver-pbl", "kirschner-minimal-guidance"] },
    rec: { status: "contextual-option", rationale: "Choose when application is the target outcome, prior knowledge exists, and facilitation plus consolidation are guaranteed." },
    tags: ["method", "transfer", "collaboration", "contested"],
  }),
  e({
    id: "guided-inquiry", label: "Guided inquiry and guided discovery", layer: "method",
    aliases: ["enhanced discovery", "structured inquiry", "guided scientific investigation"],
    summary: "Inquiry works when it is guided: unassisted discovery underperforms, while inquiry with explicit guidance, feedback, and worked support outperforms both.",
    mechanism: "Guidance keeps search within a productive space so learners test ideas rather than exhaust working memory on unconstrained exploration.",
    traditions: ["constructivist", "cognitive"], domains: ["science", "mathematics", "computing"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["explain", "practice", "transfer"], grain: "unit-course", maturity: "established",
    tasks: ["investigation design", "concept discovery", "scientific practice"],
    contexts: ["classroom", "laboratory", "simulation"],
    prereq: ["A constrained investigation space", "Explicit guidance, prompts, or worked support", "Consolidation after exploration"],
    constraints: ["The amount of guidance, not the inquiry label, drives the effect", "Younger and lower-prior-knowledge learners need more guidance", "Teacher-led inquiry activities show larger effects than pure student-led ones"],
    risks: ["Equating inquiry with minimal guidance", "Confirming misconceptions through unguided exploration", "Assessing enthusiasm instead of understanding"],
    obs: [["Concept and epistemic gains under specified guidance", "Concept measures plus records of what guidance was actually provided", "During and after the investigation", "Guidance level is often unreported, making results uninterpretable"]],
    ev: { status: "strong", confidence: "high", basis: "Meta-analyses consistently show unassisted discovery underperforms explicit instruction while guided discovery outperforms both; guidance is the decisive moderator.", directness: "direct-intervention", generalizability: "Robust across ages and science topics.", effect: { metric: "d", value: 0.5, note: "Enhanced/guided discovery versus other conditions; unassisted discovery is negative relative to explicit instruction." }, sources: ["alfieri-discovery", "furtak-inquiry", "lazonder-harmsen", "kirschner-minimal-guidance"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Adopt inquiry only with specified guidance; record the guidance level as part of the design." },
    tags: ["method", "science", "inquiry", "scaffolding"],
  }),
  e({
    id: "project-based-learning", label: "Project-based learning", layer: "method",
    aliases: ["PjBL", "extended project work"],
    summary: "Extended, driving-question projects producing public artifacts can improve academic outcomes modestly and affective outcomes more, when scaffolded and assessed carefully.",
    mechanism: "A sustained authentic goal organizes knowledge use over time and supports motivation, provided instruction is embedded rather than assumed.",
    traditions: ["constructivist", "instructional-design"], domains: ["general", "science", "engineering-design", "computing"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["transfer", "motivate", "collaborate"], grain: "unit-course", maturity: "consolidating",
    tasks: ["integrative application", "design tasks", "authentic products"],
    contexts: ["classroom", "makerspace", "workplace learning"],
    prereq: ["Embedded direct instruction on required knowledge", "Milestones and formative checkpoints", "Individual as well as group assessment"],
    constraints: ["Artifact quality is not evidence of individual learning", "Effects are modest and heterogeneous, with weak implementation fidelity reporting", "Project time competes with content coverage"],
    risks: ["Craft activity displacing conceptual learning", "Grading the poster rather than the understanding", "Unequal division of labour hiding non-learners"],
    obs: [["Individual conceptual gain alongside the artifact", "Individual assessment of target concepts plus milestone checks", "Across the project and after", "Group artifacts systematically overstate individual learning"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analysis finds moderate positive average effects with substantial heterogeneity and mixed implementation quality.", directness: "direct-intervention", generalizability: "Varies widely by discipline, duration, and scaffolding.", sources: ["chen-pbl-meta", "education-life-work"] },
    rec: { status: "contextual-option", rationale: "Use for integrative application with embedded instruction and individual assessment; do not expect coverage gains." },
    tags: ["method", "transfer", "engagement", "artifact"],
  }),
  e({
    id: "flipped-classroom", label: "Flipped classroom", layer: "method",
    aliases: ["inverted classroom", "pre-class video with in-class practice"],
    summary: "Moving first exposure before class and using class time for practice and feedback yields a small positive average effect on learning.",
    mechanism: "Class time is reallocated from transmission to guided practice with feedback; the gain depends on what actually fills the reclaimed time.",
    traditions: ["instructional-design"], domains: ["general", "science", "mathematics", "digital-environments"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["practice", "feedback", "sequence"], grain: "unit-course", maturity: "consolidating",
    tasks: ["procedural practice", "concept application", "course redesign"],
    contexts: ["higher education", "secondary classroom", "blended programs"],
    prereq: ["Reliable pre-class access for every learner", "Accountability for pre-class work", "A designed in-class activity, not free time"],
    constraints: ["The effect comes from the in-class redesign, not the video", "Adding pre-class work without removing anything increases total load", "Access inequities directly become learning inequities"],
    risks: ["Assuming video watching happened", "Doubling workload rather than reallocating it", "Widening gaps for learners without home connectivity"],
    obs: [["Learning versus the same course unflipped", "Common assessments plus pre-class completion and in-class activity records", "Across a term", "Satisfaction ratings often drop even when learning rises"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analysis finds a small positive average effect on learning with no consistent satisfaction advantage; quizzing on pre-class material is a positive moderator.", directness: "direct-intervention", generalizability: "Mostly higher education and secondary; heterogeneous designs.", effect: { metric: "g", value: 0.36, note: "Small positive effect on learning outcomes; near-zero on student satisfaction." }, sources: ["vanalten-flipped", "bernard-distance"] },
    rec: { status: "contextual-option", rationale: "Worthwhile only if the reclaimed class time is redesigned for practice and feedback and access is guaranteed." },
    tags: ["method", "digital", "practice", "sequence"],
  }),
  e({
    id: "blended-online-learning", label: "Blended and online learning designs", layer: "method",
    aliases: ["distance education", "hybrid courses", "e-learning"],
    summary: "Medium alone does not determine outcomes; blended designs tend to outperform both pure online and pure classroom, and interaction design explains most of the variance.",
    mechanism: "Learning depends on the instructional method, interaction, and support that the medium carries, not on delivery mode itself.",
    traditions: ["instructional-design"], domains: ["digital-environments", "general", "professional-workplace"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["sequence", "collaborate", "access"], grain: "program-system", maturity: "established",
    tasks: ["course delivery design", "programme scaling", "remote instruction"],
    contexts: ["higher education", "workplace learning", "adaptive software"],
    prereq: ["Designed interaction with content, peers, and instructor", "Reliable access and technical support", "Self-regulation support for asynchronous work"],
    constraints: ["Average effects are near zero with huge heterogeneity", "Comparisons are confounded by learner selection and added time", "Completion and equity outcomes often diverge from learning outcomes"],
    risks: ["Attributing gains to a platform rather than a design", "Ignoring the access and self-regulation demands placed on learners", "Reading low completion as low learner ability"],
    obs: [["Learning and completion by design feature", "Common assessment plus interaction-type and completion analytics disaggregated by subgroup", "Across the course", "Selection effects dominate naive online-versus-classroom comparisons"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Large meta-analyses show negligible medium effects overall, with blended advantage and interaction treatment as the reliable moderators.", directness: "direct-intervention", generalizability: "Broad but heterogeneous; strongest evidence at postsecondary level.", sources: ["bernard-distance", "postsecondary-tech-wwc", "garrison-coi"] },
    rec: { status: "contextual-option", rationale: "Design for interaction and support; never claim a benefit from the delivery mode itself." },
    tags: ["method", "digital", "access", "design"],
  }),
  e({
    id: "game-based-learning", label: "Serious games and game-based learning", layer: "method",
    aliases: ["educational games", "digital game-based learning"],
    summary: "Well-designed instructional games can improve learning modestly relative to conventional instruction, especially when supplemented with other instruction and played over multiple sessions.",
    mechanism: "Games provide continuous responding, immediate consequence feedback, and goal structures, but only the instructionally aligned parts produce learning.",
    traditions: ["instructional-design", "motivational-social"], domains: ["digital-environments", "science", "mathematics", "general"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["practice", "motivate", "feedback"], grain: "unit-course", maturity: "consolidating",
    tasks: ["procedural practice", "system understanding", "simulation of consequences"],
    contexts: ["adaptive software", "classroom", "home learning"],
    prereq: ["Alignment of game mechanics with the target knowledge", "Supplementary instruction and debriefing", "Multiple sessions"],
    constraints: ["Effects depend on design, not on being a game", "Motivation gains do not reliably follow", "Off-task play consumes time invisibly"],
    risks: ["Assuming engagement equals learning", "Mechanics that reward speed over reasoning", "Buying a game and skipping the surrounding instruction"],
    obs: [["Learning outside the game", "Transfer assessment outside the game environment plus time-on-task logs", "After multiple sessions", "In-game scores mostly measure game skill"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analyses find small-to-moderate learning advantages over conventional instruction, moderated by supplementary instruction and number of sessions; motivation effects are not consistent.", directness: "direct-intervention", generalizability: "Heterogeneous across genres, ages, and subjects.", effect: { metric: "d", value: 0.29, note: "Learning advantage over conventional instruction; motivation effects not reliably positive." }, sources: ["wouters-serious-games", "clark-digital-games"] },
    rec: { status: "contextual-option", rationale: "Judge the instructional design, not the format; require an out-of-game transfer measure." },
    tags: ["method", "digital", "engagement", "practice"],
  }),
  e({
    id: "gamification-reward-layers", label: "Gamification of non-game learning activities", layer: "tactic",
    aliases: ["points, badges, leaderboards", "PBL mechanics"],
    summary: "Adding game elements such as points, badges, and leaderboards to ordinary activities produces small positive effects on cognitive and behavioural outcomes and is highly design-dependent.",
    mechanism: "Game elements can add goal clarity and progress feedback; competitive elements can also crowd out interest and disadvantage lower performers.",
    traditions: ["motivational-social", "behavioral"], domains: ["digital-environments", "general"], stages: ["primary", "middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["motivate", "feedback"], grain: "micro-move", maturity: "consolidating",
    tasks: ["practice adherence", "habit formation", "progress visibility"],
    contexts: ["adaptive software", "training platforms", "classroom systems"],
    prereq: ["An activity that is worth doing repeatedly", "Progress signals tied to real learning, not clicks"],
    constraints: ["Effects are small and vary by element type", "Public leaderboards can harm lower-performing learners", "Extrinsic rewards can undermine existing intrinsic interest"],
    risks: ["Optimizing streaks and points over understanding", "Ranking learners publicly", "Manufacturing compliance and calling it motivation"],
    obs: [["Learning and voluntary persistence", "Learning outcomes plus voluntary return after rewards stop, disaggregated by performance band", "During and after removal of the mechanics", "Engagement metrics rise most for those already succeeding"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analysis finds small positive average effects on cognitive, motivational, and behavioural outcomes with strong dependence on which elements are used.", directness: "direct-intervention", generalizability: "Broad but element-specific; competitive elements are the riskiest.", effect: { metric: "g", value: 0.49, note: "Cognitive outcomes; motivational and behavioural effects smaller." }, sources: ["sailer-gamification", "ryan-deci-sdt"] },
    rec: { status: "contextual-option", rationale: "Prefer progress and mastery signals over competition; check effects for the lowest-performing band separately." },
    tags: ["tactic", "motivation", "digital", "risk"],
  }),
  e({
    id: "simulations-virtual-labs", label: "Computer simulations and virtual laboratories", layer: "method",
    aliases: ["virtual labs", "interactive simulations", "microworlds"],
    summary: "Simulations support conceptual learning when combined with guidance, and can equal or exceed physical labs for concept-focused goals.",
    mechanism: "Learners can manipulate variables, see otherwise invisible relationships, and run many trials quickly, provided assignments constrain what they attend to.",
    traditions: ["constructivist", "cognitive"], domains: ["science", "engineering-design", "mathematics", "digital-environments"], stages: ["middle", "secondary", "postsecondary"],
    functions: ["explain", "practice", "transfer"], grain: "lesson", maturity: "established",
    tasks: ["variable relationships", "model exploration", "experiment design"],
    contexts: ["laboratory", "classroom", "adaptive software", "home learning"],
    prereq: ["Assignments and prompts that direct attention", "Prior knowledge of the represented variables", "Debriefing that links the simulation to the concept"],
    constraints: ["Unguided simulation use produces weak results", "A simulation is a model, and its simplifications teach too", "Physical manipulation goals are not substituted"],
    risks: ["Treating the simulation as self-teaching", "Learners inferring the model's artefacts as physical facts", "Replacing hands-on skills that the curriculum requires"],
    obs: [["Concept gain plus model awareness", "Conceptual pre-post, prediction tasks, and questions about model limits", "During and after the sequence", "Fluent simulation manipulation can mask conceptual confusion"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Reviews find simulations generally beneficial for conceptual outcomes when supported by guidance, with comparisons to physical labs favouring neither uniformly.", directness: "direct-intervention", generalizability: "Science and engineering topics with clear variable structure.", sources: ["dejong-simulations", "rutten-simulations", "science-framework"] },
    rec: { status: "contextual-option", rationale: "Use with directed assignments and debriefing; state explicitly what the model omits." },
    tags: ["method", "science", "digital", "inquiry"],
  }),
  e({
    id: "homework-practice", label: "Homework as distributed practice", layer: "tactic",
    aliases: ["out-of-class practice", "independent assignments"],
    summary: "Homework's association with achievement is near zero in primary school and grows with age; the quality and purpose of the task matters more than the amount.",
    mechanism: "Out-of-class work can provide spacing and retrieval, but only if the task is practicable independently and errors are corrected afterwards.",
    traditions: ["behavioral", "instructional-design"], domains: ["general"], stages: ["primary", "middle", "secondary"],
    functions: ["practice", "consolidate"], grain: "micro-move", maturity: "established",
    tasks: ["retention practice", "prerequisite maintenance", "preparation"],
    contexts: ["home learning", "classroom systems"],
    prereq: ["The learner can do it without help", "Feedback on it afterwards", "Home conditions that permit it"],
    constraints: ["Age moderates the association strongly", "Correlational evidence dominates; causal claims are weak", "Home resource inequality is directly transmitted into outcomes"],
    risks: ["Assigning new material as homework", "Amplifying inequity between home environments", "Uncorrected practice consolidating errors"],
    obs: [["Independent completion and later retention", "Completion without assistance plus delayed in-class retrieval performance", "Following assignment and later", "Completion rate says nothing about who did it"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Synthesis of largely correlational studies showing a strong age gradient and dependence on task design.", directness: "mixed-direct-and-inferential", generalizability: "Association near zero for young children, moderate for secondary.", effect: { metric: "r", note: "Effectively zero in elementary grades; increasing through secondary school." }, sources: ["cooper-homework", "ies-study"] },
    rec: { status: "contextual-option", rationale: "Justify each assignment by spacing or retrieval purpose; never assign unlearned material, and check equity of home conditions." },
    tags: ["tactic", "practice", "equity", "spacing"],
  }),
  e({
    id: "differentiated-instruction", label: "Differentiated instruction (within-class)", layer: "method",
    aliases: ["within-class differentiation", "tiered tasks"],
    summary: "Adapting task, pace, or support to assessed within-class differences shows small positive effects, with data-driven and homogeneous-subgroup forms best evidenced.",
    mechanism: "Matching task demand to assessed current performance keeps more learners in a productive range than a single whole-class task.",
    traditions: ["instructional-design", "critical-equity"], domains: ["general", "mathematics", "literacy"], stages: ["primary", "middle", "secondary"],
    functions: ["diagnose", "sequence", "access"], grain: "lesson", maturity: "consolidating",
    tasks: ["mixed-attainment classes", "targeted practice", "within-class grouping"],
    contexts: ["classroom", "small group", "adaptive software"],
    prereq: ["Current assessment data at task grain", "Genuinely different tasks, not just more or fewer items", "Teacher time and materials"],
    constraints: ["Evidence base is thin and definitions vary enormously", "Differentiation by fixed learner label is not supported", "Curriculum entitlement must not be reduced for lower groups"],
    risks: ["Permanently lowering expectations for a subgroup", "Differentiating by supposed learning style or ability label", "Unsustainable teacher workload leading to token differentiation"],
    obs: [["Growth across all attainment bands", "Band-disaggregated growth on common outcomes plus curriculum-coverage audit", "Across a term", "Overall gains can hide losses for the lowest band"]],
    ev: { status: "context-dependent", confidence: "low", basis: "Meta-analytic review finds small positive effects for specific data-driven forms, with weak and inconsistent evidence for differentiation as a general practice.", directness: "direct-intervention", generalizability: "Primary and lower-secondary; heavily dependent on how differentiation is operationalized.", sources: ["deunk-differentiation", "steenbergen-grouping"] },
    rec: { status: "contextual-option", rationale: "Differentiate on current task evidence with equal curriculum entitlement; never on a stable learner label." },
    tags: ["method", "adaptive", "equity", "diagnostic"],
  }),
];
