import { e } from "../lib.mjs";

export default [
  e({
    id: "elaborative-interrogation", label: "Elaborative interrogation", layer: "tactic",
    aliases: ["why questions", "elaborative questioning"],
    summary: "Prompt the learner to explain why a stated fact is true, linking it to what they already know.",
    mechanism: "Generating a reason integrates the new fact with existing knowledge and exposes gaps that passive reading leaves hidden.",
    traditions: ["cognitive"], domains: ["general", "science"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["practice", "consolidate"], grain: "micro-move", maturity: "established",
    tasks: ["factual learning with underlying reasons", "text study", "concept consolidation"],
    contexts: ["study strategies", "classroom questioning", "adaptive software"],
    prereq: ["Some relevant prior knowledge to elaborate from", "Facts that actually have explanations"],
    constraints: ["Benefits shrink when prior knowledge is very low", "Not applicable to arbitrary associations", "Learner-generated explanations may be wrong and need checking"],
    risks: ["Accepting fluent but incorrect explanations", "Using it for arbitrary facts where no reason exists", "Adding time without checking the elaboration's accuracy"],
    obs: [["Accuracy of generated reasons", "Coding of explanation correctness plus delayed factual and inference tests", "During study and at delay", "Verbose explanations are not better explanations"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Rated moderate utility in a comprehensive evidence review; benefits established mainly for factual material with existing prior knowledge.", directness: "direct-intervention", generalizability: "Mostly laboratory and short classroom studies with factual content.", sources: ["dunlosky-techniques", "chi-self-explanation"] },
    rec: { status: "contextual-option", rationale: "Cheap addition for explainable facts; verify the generated explanation rather than assuming it." },
    tags: ["tactic", "elaboration", "explanation", "memory"],
  }),
  e({
    id: "summarization-training", label: "Summarization as a study strategy", layer: "tactic",
    aliases: ["writing summaries", "gist extraction"],
    summary: "Summarizing helps only when learners have been trained to produce good summaries; untrained summarization is a low-utility strategy.",
    mechanism: "Selecting main ideas and condensing forces processing of structure, but poor summaries copy surface sentences and add nothing.",
    traditions: ["cognitive"], domains: ["literacy", "general"], stages: ["middle", "secondary", "postsecondary"],
    functions: ["consolidate", "self-regulate"], grain: "micro-move", maturity: "established",
    tasks: ["text comprehension", "study review", "note consolidation"],
    contexts: ["study strategies", "classroom", "writing tasks"],
    prereq: ["Explicit training in summarization criteria", "Feedback on summary quality"],
    constraints: ["Effects depend on training that is often long", "Weak readers copy rather than condense", "Rated low utility relative to retrieval and spacing"],
    risks: ["Assuming summarizing is inherently generative", "Substituting it for retrieval practice", "Grading length rather than selection quality"],
    obs: [["Summary quality and later comprehension", "Rubric scoring of idea selection plus delayed comprehension of new text", "After training and at delay", "A neat summary can be pure transcription"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Comprehensive review rates summarization low utility overall, with benefits conditional on substantial training.", directness: "direct-intervention", generalizability: "Mostly text-based academic tasks with older learners.", sources: ["dunlosky-techniques", "graham-perin-writing"] },
    rec: { status: "contextual-option", rationale: "Only worth recommending with explicit criteria and feedback; prefer retrieval when the goal is retention." },
    tags: ["tactic", "literacy", "consolidation", "contested"],
  }),
  e({
    id: "concept-mapping", label: "Concept mapping and graphic organizers", layer: "tactic",
    aliases: ["knowledge maps", "graphic organizers"],
    summary: "Constructing or studying node-link maps of relationships modestly improves learning relative to reading, but is weaker than retrieval practice for retention.",
    mechanism: "Explicit relational structure supports organization and retrieval cues; making relations visible exposes missing links.",
    traditions: ["cognitive", "constructivist"], domains: ["general", "science"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["consolidate", "explain"], grain: "micro-move", maturity: "established",
    tasks: ["relational understanding", "review", "knowledge organization"],
    contexts: ["study strategies", "classroom", "note-taking"],
    prereq: ["Content with genuine relational structure", "Some training in map conventions"],
    constraints: ["Effect is modest and depends on map quality", "Map-making time competes with retrieval practice", "A tidy map can be copied without understanding"],
    risks: ["Substituting map aesthetics for reasoning", "Choosing mapping over retrieval when retention is the goal", "Assuming the map represents the learner's actual model"],
    obs: [["Relational accuracy and later performance", "Map scoring against an expert structure plus delayed comprehension or transfer items", "After construction and at delay", "Map completeness overstates understanding"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Meta-analysis shows small-to-moderate advantages over reading or lecture; a direct comparison found retrieval practice superior for retention.", directness: "direct-intervention", generalizability: "Broad across ages and subjects for relational content.", effect: { metric: "d", value: 0.35, note: "Versus reading or attending lectures; smaller versus other constructive activities." }, sources: ["nesbit-concept-mapping", "karpicke-blunt"] },
    rec: { status: "contextual-option", rationale: "Good for making structure explicit; do not use it in place of retrieval practice for retention goals." },
    tags: ["tactic", "representation", "knowledge", "consolidation"],
  }),
  e({
    id: "note-taking", label: "Note-taking format and generative processing", layer: "tactic",
    aliases: ["longhand versus laptop notes", "guided notes"],
    summary: "Notes help most when they require selection and paraphrase rather than verbatim capture; the specific claim that longhand beats typing has not replicated reliably.",
    mechanism: "Selecting and rephrasing forces processing during encoding and produces a better external record for later retrieval practice.",
    traditions: ["cognitive"], domains: ["general"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["consolidate", "self-regulate"], grain: "micro-move", maturity: "disputed",
    tasks: ["lecture learning", "reading study", "meeting and training capture"],
    contexts: ["higher education", "classroom", "workplace learning"],
    prereq: ["Time to review the notes later", "Enough background to select what matters"],
    constraints: ["Medium matters less than the processing it induces", "Original longhand-versus-laptop findings failed to replicate at scale", "Note quality depends on prior knowledge"],
    risks: ["Banning devices on the strength of a non-replicated finding", "Creating a transcript that is never revisited", "Accessibility harm when handwriting is mandated"],
    obs: [["Paraphrase rate and later retrieval", "Note coding for verbatim versus paraphrase plus delayed test performance", "During and after study", "Longer notes are not better notes"]],
    ev: { status: "contested", confidence: "moderate", basis: "The influential longhand-advantage experiment failed to replicate in a large direct replication; the general generative-processing account remains supported.", directness: "direct-intervention", generalizability: "Higher education lecture settings dominate the evidence.", sources: ["mueller-oppenheimer", "morehead-replication", "dunlosky-techniques"] },
    rec: { status: "do-not-generalize", rationale: "Recommend generative note-taking and later review; do not issue a handwriting-versus-typing mandate, which also raises accessibility problems." },
    tags: ["tactic", "contested", "consolidation", "accessibility"],
  }),
  e({
    id: "pretesting", label: "Pretesting and prequestioning", layer: "tactic",
    aliases: ["errorful pretesting", "prequestions", "the pretesting effect"],
    summary: "Attempting questions before instruction, even with wrong answers, improves later learning of the tested material.",
    mechanism: "A failed retrieval attempt activates related knowledge and directs attention during subsequent study to the gap it exposed.",
    traditions: ["cognitive"], domains: ["general"], stages: ["middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["diagnose", "practice"], grain: "micro-move", maturity: "consolidating",
    tasks: ["preparation for instruction", "reading preparation", "lecture priming"],
    contexts: ["classroom", "adaptive software", "study strategies"],
    prereq: ["Subsequent instruction or feedback that resolves the question", "Low stakes and explicit permission to be wrong"],
    constraints: ["Benefits concentrate on the pretested material and may not spread to untested content", "Requires the follow-up study phase", "Errors must be corrected or they can persist"],
    risks: ["Framing pretests as evaluation, which raises anxiety", "Leaving errors uncorrected", "Assuming a benefit for untested related material"],
    obs: [["Post-instruction performance on pretested versus untested items", "Split-item design comparing pretested and non-pretested content", "After instruction and at delay", "Benefit may not generalize beyond the pretested items"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Replicated experimental effect with clear boundary conditions around subsequent study and item specificity.", directness: "direct-intervention", generalizability: "Mostly laboratory and classroom studies with verbal material.", sources: ["richland-pretesting", "metcalfe-errors", "bjork-self-regulated"] },
    rec: { status: "contextual-option", rationale: "Cheap and useful before instruction, provided errors are explicitly resolved afterwards and stakes are zero." },
    tags: ["tactic", "diagnostic", "memory", "generation"],
  }),
  e({
    id: "generation-effect", label: "Generation effect", layer: "tactic",
    aliases: ["generate rather than read", "productive generation"],
    summary: "Information a learner generates is remembered better than the same information read, provided generation succeeds or is corrected.",
    mechanism: "Generating engages the retrieval and construction processes that later recall depends on, creating a stronger and more distinctive trace.",
    traditions: ["cognitive"], domains: ["general"], stages: ["cross-lifespan"],
    functions: ["practice", "consolidate"], grain: "micro-move", maturity: "established",
    tasks: ["vocabulary", "definitions", "procedure steps"],
    contexts: ["study strategies", "adaptive software", "classroom questioning"],
    prereq: ["Enough knowledge to attempt generation", "Immediate correction available"],
    constraints: ["Fails without adequate prior knowledge or feedback", "Effect sizes are modest for complex material", "Time cost per item is higher than reading"],
    risks: ["Uncorrected generation consolidating errors", "Applying it to material with no basis for generation", "Confusing it with unguided discovery of new concepts"],
    obs: [["Recall for generated versus read items", "Within-subject item comparison at delay", "After a delay", "Generation is slower per item; compare per unit time as well"]],
    ev: { status: "strong", confidence: "high", basis: "A classic and widely replicated memory effect, with modern reviews clarifying that errorful generation also helps when feedback follows.", directness: "direct-intervention", generalizability: "Robust for verbal material; smaller and more conditional for complex content.", sources: ["slamecka-generation", "metcalfe-errors", "dunlosky-techniques"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Prefer generation over presentation whenever feedback can immediately follow." },
    tags: ["tactic", "generation", "memory", "practice"],
  }),
  e({
    id: "errorful-learning", label: "Errorful learning and the hypercorrection effect", layer: "tactic",
    aliases: ["learning from errors", "hypercorrection", "productive error"],
    summary: "Errors made with feedback support learning, and confidently held errors are especially likely to be corrected and stay corrected.",
    mechanism: "An error creates a discrepancy that draws attention to the feedback; high-confidence errors produce surprise, which enhances encoding of the correction.",
    traditions: ["cognitive"], domains: ["general"], stages: ["cross-lifespan"],
    functions: ["feedback", "practice", "climate"], grain: "micro-move", maturity: "established",
    tasks: ["misconception correction", "quiz feedback", "skill practice"],
    contexts: ["classroom", "adaptive software", "tutoring", "low-stakes quiz"],
    prereq: ["Feedback that actually follows the error", "Psychological safety to be wrong", "Attention to the corrective information"],
    constraints: ["Without feedback, errors can persist", "The benefit is about learning, not about arranging failure for its own sake", "Public error exposure carries social cost"],
    risks: ["Designing for failure without guaranteeing correction", "Exposing errors publicly in unsafe climates", "Assuming error rate itself is a goal"],
    obs: [["Correction durability by pre-error confidence", "Track error, confidence, feedback, and later retention of the correction", "Immediately and at delay", "Uncorrected errors are consolidated by the same mechanism"]],
    ev: { status: "strong", confidence: "high", basis: "A well-replicated body of experiments, reviewed comprehensively, showing errors followed by feedback benefit learning and that high-confidence errors are corrected most readily.", directness: "direct-intervention", generalizability: "Broad across ages and materials where feedback is provided.", sources: ["metcalfe-errors", "feedback-meta", "hattie-timperley-feedback"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Design for errors plus guaranteed correction and safety; never for errors alone." },
    tags: ["tactic", "feedback", "error", "climate"],
  }),
  e({
    id: "spaced-repetition-scheduling", label: "Algorithmic spaced repetition", layer: "tactic",
    aliases: ["spaced education", "flashcard scheduling", "expanding retrieval schedules"],
    summary: "Software that schedules review by predicted forgetting sustains retention of large item sets efficiently, including for busy professionals.",
    mechanism: "Reviews are placed near the point of forgetting, combining spacing and retrieval so each review yields maximum retention gain per minute.",
    traditions: ["cognitive", "behavioral"], domains: ["general", "world-language", "health", "professional-workplace"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["practice", "consolidate"], grain: "micro-move", maturity: "established",
    tasks: ["vocabulary", "terminology", "facts and classifications", "recertification"],
    contexts: ["adaptive software", "flashcards", "workplace recertification"],
    prereq: ["Well-formed atomic items", "Initial understanding before memorization", "Sustained access over time"],
    constraints: ["Optimal gap depends on the retention horizon", "Item quality dominates algorithm choice", "It builds recall, not application or judgment"],
    risks: ["Memorizing items that were never understood", "Endless review backlogs causing abandonment", "Treating fact recall as the whole curriculum"],
    obs: [["Retention per review minute", "Delayed recall plus review-time logs and lapse rate", "Across weeks and months", "In-app accuracy is inflated by recent scheduling"]],
    ev: { status: "strong", confidence: "high", basis: "Spacing meta-analysis plus randomized trials of spaced education in professional settings show durable retention advantages.", directness: "direct-intervention", generalizability: "Strong for well-formed recall items; not evidence for complex reasoning outcomes.", sources: ["spacing-meta", "kerfoot-spaced-education", "dunlosky-techniques"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Default for durable factual and terminological knowledge; pair with application practice for anything more." },
    tags: ["tactic", "spacing", "memory", "digital"],
  }),
  e({
    id: "wait-time", label: "Wait time after questions", layer: "tactic",
    aliases: ["think time", "pause after questioning"],
    summary: "Extending the pause after a question, and after the learner's answer, to several seconds changes the length, quality, and distribution of responses.",
    mechanism: "Silence gives time to retrieve and formulate rather than to react, and it changes who is able to enter the conversation.",
    traditions: ["cognitive", "sociocultural"], domains: ["general"], stages: ["primary", "middle", "secondary", "postsecondary"],
    functions: ["explain", "collaborate", "access"], grain: "micro-move", maturity: "established",
    tasks: ["classroom questioning", "discussion", "checking for understanding"],
    contexts: ["classroom", "small group", "tutoring", "live online"],
    prereq: ["A question worth thinking about", "Tolerance for silence"],
    constraints: ["Original effects come from a modest observational and quasi-experimental base", "Wait time alone does not improve a low-quality question", "Cultural norms about silence differ"],
    risks: ["Extending wait after trivial recall questions", "Using silence as pressure on one learner", "Assuming better talk means better learning without measuring"],
    obs: [["Response length and participation spread", "Timed response length, number of distinct responders, and reasoning quality", "During questioning episodes", "More talk is not automatically more learning"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Classic classroom research with consistent observational findings; modern causal evidence on learning outcomes is limited.", directness: "mixed-direct-and-inferential", generalizability: "Widely applicable; effects reported mainly on discourse rather than achievement.", sources: ["rowe-wait-time", "rosenshine-principles"] },
    rec: { status: "contextual-option", rationale: "Near-zero-cost discourse improvement; pair it with better questions rather than treating it as an achievement intervention." },
    tags: ["tactic", "questioning", "participation", "equity"],
  }),
  e({
    id: "checking-for-understanding", label: "Systematic checking for understanding", layer: "tactic",
    aliases: ["hinge questions", "all-student response", "responsive questioning"],
    summary: "Frequent questions answered by every learner, used to decide the next instructional move, catch misunderstanding before it is practised.",
    mechanism: "Sampling every learner's current state converts teaching from broadcast into a control loop with an actual measurement.",
    traditions: ["instructional-design", "psychometric"], domains: ["general"], stages: ["primary", "middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["diagnose", "feedback", "assess"], grain: "micro-move", maturity: "established",
    tasks: ["lesson-level monitoring", "misconception detection", "pacing decisions"],
    contexts: ["classroom", "live online", "tutoring", "adaptive software"],
    prereq: ["Questions whose wrong answers are diagnostic", "A response channel for every learner", "A planned action for each likely result"],
    constraints: ["Only formative if it changes the next action", "Hands-up sampling systematically misses those who need it", "Question design determines the diagnostic value"],
    risks: ["Asking 'any questions?' and calling it a check", "Collecting responses without acting on them", "Public exposure of struggling learners"],
    obs: [["Detection rate and responsive action", "Proportion of learners sampled, error patterns detected, and documented change in the next move", "Every few minutes of instruction", "A high correct rate may mean the question was too easy"]],
    ev: { status: "strong", confidence: "moderate", basis: "Convergent support from expert-teacher process research, practice-guide recommendations, and the formative assessment literature.", directness: "mixed-direct-and-inferential", generalizability: "Broad; the diagnostic quality of the questions is the limiting factor.", sources: ["rosenshine-principles", "wiliam-assessment", "formative-review"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Default instructional control loop; require diagnostic distractors and a pre-planned response." },
    tags: ["tactic", "diagnostic", "feedback", "assessment"],
  }),
  e({
    id: "analogical-case-comparison", label: "Analogical comparison of cases", layer: "tactic",
    aliases: ["case comparison", "structural alignment", "compare two examples"],
    summary: "Comparing two or more cases side by side and stating what they share promotes abstraction of the deep structure and later transfer.",
    mechanism: "Structural alignment forces attention to relations rather than surface features, producing a more portable schema than a single case does.",
    traditions: ["cognitive"], domains: ["general", "mathematics", "science", "professional-workplace"], stages: ["middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["transfer", "explain"], grain: "micro-move", maturity: "established",
    tasks: ["principle abstraction", "transfer preparation", "negotiation and judgment training"],
    contexts: ["classroom", "professional education", "instructional materials"],
    prereq: ["At least two cases sharing deep structure with different surfaces", "An explicit prompt to compare and state the commonality"],
    constraints: ["Merely presenting cases without comparison prompts does little", "Cases must differ on surface and match on structure", "Novices may align on the wrong features without guidance"],
    risks: ["Comparison prompts that elicit surface similarity", "Too many cases at once overloading novices", "Assuming spontaneous transfer without the explicit prompt"],
    obs: [["Stated principle and later spontaneous transfer", "Quality of the stated commonality plus performance on a new surface-different case", "After comparison and at delay", "Correct comparison does not guarantee spontaneous later use"]],
    ev: { status: "strong", confidence: "moderate", basis: "Controlled experiments show explicit comparison substantially raises later transfer relative to studying cases separately.", directness: "direct-intervention", generalizability: "Demonstrated from classroom topics to professional negotiation training.", sources: ["gentner-analogical", "transfer-taxonomy", "rittle-johnson-star-comparison"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "One of the few reliable levers on transfer; require an explicit comparison prompt, not just co-presentation." },
    tags: ["tactic", "transfer", "comparison", "abstraction"],
  }),
  e({
    id: "contrasting-cases-invention", label: "Contrasting cases and invention before instruction", layer: "tactic",
    aliases: ["inventing to prepare for future learning", "preparation for future learning"],
    summary: "Having learners invent an account of carefully contrasted cases before being told the canonical solution prepares them to learn from the subsequent explanation.",
    mechanism: "Attempting invention differentiates the features that matter, so the later explanation lands on a prepared discrimination rather than on undifferentiated novelty.",
    traditions: ["constructivist", "cognitive"], domains: ["mathematics", "science", "general"], stages: ["middle", "secondary", "postsecondary"],
    functions: ["transfer", "practice", "explain"], grain: "lesson", maturity: "consolidating",
    tasks: ["quantitative concept introduction", "deep-feature discrimination", "transfer preparation"],
    contexts: ["classroom", "tutoring", "instructional materials"],
    prereq: ["Case sets engineered to contrast on the target feature", "A guaranteed consolidation phase afterwards", "Tolerance for initial failure"],
    constraints: ["The invention phase must be followed by explicit instruction", "Effects appear on transfer measures more than on routine ones", "Requires careful case engineering; arbitrary examples do not work"],
    risks: ["Omitting the consolidation and leaving inventions unresolved", "Judging the phase by the quality of the invention", "Using it with learners lacking the needed prerequisites"],
    obs: [["Preparation for future learning", "Transfer and learning-from-resource measures, not just routine post-tests", "After consolidation and at delay", "Routine post-tests often show no advantage even when transfer does"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Controlled studies plus the productive-failure meta-analysis support a generate-then-consolidate sequence for conceptual and transfer outcomes.", directness: "direct-intervention", generalizability: "Mathematics and science concepts with engineered contrasting cases.", sources: ["schwartz-martin-invention", "productive-failure-meta"] },
    rec: { status: "contextual-option", rationale: "Use where transfer is the goal and consolidation is guaranteed; the contrasting-case design is the active ingredient." },
    tags: ["tactic", "transfer", "generation", "comparison"],
  }),
  e({
    id: "gesture-and-embodiment", label: "Gesture and embodied representation", layer: "tactic",
    aliases: ["instructional gesture", "producing gestures while explaining"],
    summary: "Producing and observing task-relevant gestures supports learning of spatial and relational content and can make emerging understanding visible.",
    mechanism: "Gesture externalizes spatial and relational structure, offloads working memory, and expresses knowledge a learner cannot yet verbalize.",
    traditions: ["cognitive", "developmental", "neuroscience"], domains: ["mathematics", "science", "world-language"], stages: ["preschool", "primary", "middle", "secondary"],
    functions: ["explain", "diagnose"], grain: "micro-move", maturity: "consolidating",
    tasks: ["spatial reasoning", "equation structure", "concept explanation"],
    contexts: ["classroom", "tutoring", "video instruction"],
    prereq: ["Content with spatial or relational structure", "A gesture that maps to that structure"],
    constraints: ["Arbitrary gestures do not help", "Evidence is strongest for children and spatial or mathematical content", "Accessibility alternatives are needed for learners who cannot see or produce gestures"],
    risks: ["Adding decorative movement", "Requiring gesture in ways that exclude some learners", "Reading gesture as proficiency"],
    obs: [["Gesture-speech mismatch and learning readiness", "Coded gesture during explanation plus post-instruction performance", "During explanation and after instruction", "Mismatch signals readiness, not mastery"]],
    ev: { status: "context-dependent", confidence: "moderate", basis: "Experimental work shows gesture production causally aids learning of mathematical and spatial content and reveals transitional knowledge.", directness: "direct-intervention", generalizability: "Strongest for children learning spatial or mathematical relations.", sources: ["goldin-meadow-gesture", "hpl2"] },
    rec: { status: "contextual-option", rationale: "Use structurally meaningful gesture for spatial and relational content, with accessible alternatives available." },
    tags: ["tactic", "representation", "mathematics", "diagnostic"],
  }),
  e({
    id: "goal-setting-and-implementation-intentions", label: "Specific goals and implementation intentions", layer: "tactic",
    aliases: ["SMART goals", "if-then planning", "goal specificity"],
    summary: "Specific, difficult, accepted goals outperform vague ones, and if-then plans that specify when and where to act close much of the intention-action gap.",
    mechanism: "Specific goals direct attention and effort and permit self-monitoring; if-then plans delegate initiation to a situational cue rather than to willpower.",
    traditions: ["motivational-social", "behavioral"], domains: ["general", "professional-workplace"], stages: ["middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["self-regulate", "motivate"], grain: "micro-move", maturity: "established",
    tasks: ["study planning", "practice adherence", "behaviour change"],
    contexts: ["coaching", "study strategies", "workplace learning", "adaptive software"],
    prereq: ["Goal acceptance and commitment", "The skill to actually perform the action", "Feedback on progress"],
    constraints: ["Specific difficult goals harm performance on tasks still being learned", "Goals without feedback do little", "They can narrow attention and encourage gaming the metric"],
    risks: ["Setting outcome goals for skills not yet acquired", "Metric fixation and neglect of unmeasured goals", "Demoralization when goals are imposed rather than accepted"],
    obs: [["Goal-linked behaviour change", "Rate of intended action performed plus progress on the target skill", "Weekly", "Goal attainment can be met by lowering the standard"]],
    ev: { status: "strong", confidence: "high", basis: "One of the most replicated findings in organizational psychology, with a large separate literature on implementation intentions.", directness: "direct-intervention", generalizability: "Robust for performance of acquired skills; weaker or negative during acquisition.", effect: { metric: "d", value: 0.6, note: "Implementation-intention effects on goal attainment are typically medium-to-large." }, sources: ["locke-latham-goals", "zimmerman-srl"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Use learning goals during acquisition and performance goals after; always pair with progress feedback." },
    tags: ["tactic", "self-regulation", "motivation", "adult"],
  }),
  e({
    id: "feedback-design-levels", label: "Feedback levels: task, process, self-regulation, and self", layer: "principle",
    aliases: ["four levels of feedback", "feedback focus"],
    summary: "Feedback about the task, the process, and self-regulation supports learning, while feedback about the person is ineffective or harmful.",
    mechanism: "Feedback works by reducing a gap between current and desired understanding; person-directed feedback carries no gap-closing information and diverts attention to the self.",
    traditions: ["cognitive", "motivational-social"], domains: ["general", "assessment-measurement"], stages: ["cross-lifespan"],
    functions: ["feedback"], grain: "micro-move", maturity: "established",
    tasks: ["written feedback", "verbal correction", "automated feedback design"],
    contexts: ["classroom", "tutoring", "adaptive software", "workplace learning"],
    prereq: ["A clear goal the learner understands", "Information about the gap", "An opportunity to act on it"],
    constraints: ["A substantial minority of feedback interventions reduce performance", "Praise directed at the person does not improve learning", "Feedback without a chance to revise is inert"],
    risks: ["Grades crowding out attention to comments", "Person praise creating contingent self-worth", "Overwhelming volume of correction"],
    obs: [["Uptake and subsequent performance", "Evidence of the feedback being acted on plus performance on the next attempt", "Immediately after the revision opportunity", "Reading feedback is not acting on it"]],
    ev: { status: "strong", confidence: "high", basis: "Convergent evidence from the classic feedback meta-analysis, the four-level synthesis, and later meta-analyses of feedback in education.", directness: "direct-intervention", generalizability: "Broad; effect sign depends on level and on revision opportunity.", effect: { metric: "d", value: 0.48, note: "Average positive effect with wide variance; over a third of interventions in the classic meta-analysis reduced performance." }, sources: ["hattie-timperley-feedback", "feedback-meta", "wisniewski-feedback-meta", "shute-formative-feedback"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Direct feedback at task, process, or self-regulation, and always provide the revision opportunity that makes it usable." },
    tags: ["principle", "feedback", "revision", "warning"],
  }),
  e({
    id: "feedback-literacy", label: "Feedback uptake and learner feedback literacy", layer: "framework",
    aliases: ["feedback as a process", "sustainable feedback", "closing the loop"],
    summary: "Feedback only counts when the learner appreciates, judges, and acts on it, so systems must design for uptake rather than for delivery.",
    mechanism: "Learners need the capability to evaluate quality, manage the affective response, and take action; without it, well-formed comments produce nothing.",
    traditions: ["instructional-design", "sociocultural"], domains: ["general", "assessment-measurement"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["feedback", "self-regulate"], grain: "unit-course", maturity: "consolidating",
    tasks: ["assignment feedback cycles", "peer review", "coaching conversations"],
    contexts: ["higher education", "workplace learning", "classroom"],
    prereq: ["A subsequent task where the feedback applies", "Exemplars and criteria the learner can use to judge quality", "Time allocated for uptake"],
    constraints: ["Uptake capability must be developed deliberately", "Emotional response mediates use", "Evidence base is largely conceptual and higher-education-based"],
    risks: ["Measuring feedback quality by volume produced", "Assuming uptake because comments were delivered", "Blaming learners for not using feedback they were never taught to use"],
    obs: [["Documented action on feedback", "Comparison of successive drafts or attempts plus learner accounts of what they changed", "Across the feedback cycle", "Satisfaction with feedback correlates weakly with using it"]],
    ev: { status: "context-dependent", confidence: "low", basis: "A conceptual framework with growing but largely qualitative higher-education evidence; consistent with the finding that feedback needs a revision opportunity.", directness: "consensus-design", generalizability: "Mostly higher education; limited causal evidence.", sources: ["carless-feedback-literacy", "nicol-macfarlane", "sadler-formative"] },
    rec: { status: "contextual-option", rationale: "Design the uptake step explicitly and measure the change it produced, not the feedback delivered." },
    tags: ["framework", "feedback", "self-regulation", "revision"],
  }),
  e({
    id: "study-skills-programs", label: "Study-skills and learning-strategy programmes", layer: "method",
    aliases: ["learning to learn courses", "study strategy training"],
    summary: "Strategy training works best when taught in context with the content it applies to, and worst when delivered as a detached generic course.",
    mechanism: "Strategies are conditional knowledge: learners need to know when and where to apply them, which only the domain context supplies.",
    traditions: ["cognitive", "instructional-design"], domains: ["general"], stages: ["secondary", "postsecondary", "adult-workplace"],
    functions: ["self-regulate", "transfer"], grain: "unit-course", maturity: "established",
    tasks: ["study strategy development", "transition support", "academic recovery"],
    contexts: ["higher education", "secondary classroom", "coaching"],
    prereq: ["A content course the strategies are practised inside", "Metacognitive framing of when to use each strategy", "Follow-up practice"],
    constraints: ["Generic detached programmes transfer poorly", "Learners revert to familiar strategies under time pressure", "Self-reported strategy use is unreliable"],
    risks: ["Running a standalone workshop and expecting change", "Teaching low-utility strategies such as highlighting", "Measuring satisfaction rather than strategy change"],
    obs: [["Actual strategy change in course work", "Observed or logged study behaviour plus performance, not self-report alone", "Across a term", "Self-reported strategy use overstates actual change"]],
    ev: { status: "strong", confidence: "moderate", basis: "Meta-analysis of study-skills interventions finds effects depend on contextualization; near-transfer within the taught context is the reliable result.", directness: "direct-intervention", generalizability: "Secondary and higher education.", sources: ["hattie-study-skills", "dunlosky-techniques", "dignath-buttner"] },
    rec: { status: "contextual-option", rationale: "Embed strategy instruction inside a real course and teach the conditions of use, not the strategy list." },
    tags: ["method", "self-regulation", "strategy", "transfer"],
  }),
];
