import { e } from "../lib.mjs";

export default [
  e({
    id: "andragogy", label: "Andragogy (Knowles' assumptions about adult learners)", layer: "theory",
    aliases: ["adult learning principles", "Knowles' andragogy"],
    summary: "A set of assumptions that adults are self-directed, bring experience, are readiness- and problem-centred, and are internally motivated; influential as design guidance but weak as an empirical theory.",
    mechanism: "The assumptions direct designers toward autonomy, experience-linking, and immediate applicability, which map onto better-evidenced motivational and prior-knowledge findings.",
    traditions: ["instructional-design", "motivational-social"], domains: ["professional-workplace", "general"], stages: ["postsecondary", "adult-workplace", "older-adult"],
    functions: ["motivate", "sequence"], grain: "unit-course", maturity: "disputed",
    tasks: ["adult course design", "workplace training design"],
    contexts: ["workplace learning", "continuing education", "higher education"],
    prereq: ["Learners with relevant experience and a real application context"],
    constraints: ["The assumptions are not adult-specific: children also learn better with relevance and agency", "Adult status does not confer self-direction in an unfamiliar domain", "It has never been a well-tested causal theory"],
    risks: ["Withdrawing needed instruction because the learner is an adult", "Assuming experience is always an asset rather than sometimes a misconception", "Presenting andragogy as settled science"],
    obs: [["Actual self-direction in this domain", "Observed planning, monitoring, and help-seeking on a real task in the target domain", "At the start of a programme", "Confident adults frequently over-estimate their self-direction in a new domain"]],
    ev: { status: "contested", confidence: "moderate", basis: "Widely used design heuristics whose adult-specific claims are not empirically established; reviewed critically in the adult-learning literature.", directness: "consensus-design", generalizability: "Design vocabulary rather than evidence; the underlying motivational findings are better sourced elsewhere.", sources: ["merriam-adult-theory", "ryan-deci-sdt"] },
    rec: { status: "do-not-generalize", rationale: "Use the design instincts, cite the motivation and prior-knowledge evidence instead; never withhold instruction because the learner is an adult." },
    tags: ["theory", "adult", "contested", "self-direction"],
  }),
  e({
    id: "transformative-learning", label: "Transformative learning", layer: "theory",
    aliases: ["perspective transformation", "Mezirow's transformative learning"],
    summary: "Adults can undergo a shift in frame of reference through a disorienting dilemma and critical reflection, changing how they interpret experience rather than only what they know.",
    mechanism: "A dilemma the existing frame cannot accommodate prompts critical reflection on assumptions, discourse with others, and eventual reintegration under a revised frame.",
    traditions: ["constructivist", "critical-equity"], domains: ["professional-workplace", "general"], stages: ["adult-workplace", "older-adult", "postsecondary"],
    functions: ["transfer", "self-regulate", "climate"], grain: "program-system", maturity: "emerging",
    tasks: ["professional identity change", "values-laden learning", "reflective practice"],
    contexts: ["continuing education", "professional development", "coaching"],
    prereq: ["A genuine disorienting experience", "Psychological safety for critical reflection", "Discourse with others"],
    constraints: ["Evidence is largely qualitative and retrospective", "Transformation cannot be reliably engineered on a schedule", "There are real ethical limits to deliberately disorienting learners"],
    risks: ["Manufacturing distress in the name of transformation", "Claiming transformation from a satisfaction survey", "Applying it where technical skill, not perspective, is the gap"],
    obs: [["Documented frame change over time", "Longitudinal reflective evidence plus changed practice observed by others", "Over months", "Self-reported transformation is weak evidence on its own"]],
    ev: { status: "hypothesis", confidence: "low", basis: "An influential adult-education theory supported mainly by qualitative and retrospective studies rather than controlled evidence.", directness: "consensus-design", generalizability: "Adult and professional education discourse.", sources: ["mezirow-transformative", "merriam-adult-theory"] },
    rec: { status: "experimental-only", rationale: "Use as a lens for values-laden adult learning; never as a promised outcome or a justification for engineered distress." },
    tags: ["theory", "adult", "reflection", "hypothesis"],
  }),
  e({
    id: "transfer-of-training", label: "Transfer of training to the workplace", layer: "framework",
    aliases: ["training transfer", "transfer climate", "Baldwin and Ford model"],
    summary: "Whether training changes work behaviour depends on trainee characteristics, training design, and above all the work environment's transfer climate and support.",
    mechanism: "Learned capability only becomes performance where the environment provides opportunity, support, and consequences for using it.",
    traditions: ["instructional-design", "motivational-social"], domains: ["professional-workplace"], stages: ["adult-workplace"],
    functions: ["transfer", "climate"], grain: "program-system", maturity: "established",
    tasks: ["training evaluation", "workplace learning design", "performance change"],
    contexts: ["workplace learning", "professional development"],
    prereq: ["Opportunity to perform the trained behaviour", "Supervisor and peer support", "Measurement beyond course completion"],
    constraints: ["Environment factors often dominate design factors", "Self-reported transfer overstates behaviour change", "Transfer decays without reinforcement"],
    risks: ["Evaluating training by satisfaction or completion", "Blaming trainees for an unsupportive environment", "Training a behaviour the workplace actively penalizes"],
    obs: [["Observed behaviour change on the job", "Supervisor or record-based behaviour measures plus transfer-climate assessment", "Weeks to months after training", "Course completion and satisfaction predict transfer poorly"]],
    ev: { status: "strong", confidence: "high", basis: "The foundational transfer model plus a large meta-analysis identifying transfer climate, support, and motivation as the strongest predictors.", directness: "mixed-direct-and-inferential", generalizability: "Organizational training broadly.", sources: ["baldwin-ford", "blume-transfer-meta", "arthur-training-meta"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Design and evaluate the environment, not just the course; never claim transfer from completion data." },
    tags: ["framework", "adult", "workplace", "transfer"],
  }),
  e({
    id: "training-design-effectiveness", label: "Training design and evaluation criteria", layer: "principle",
    aliases: ["needs assessment, practice, feedback", "Kirkpatrick criteria caution"],
    summary: "Organizational training works when needs assessment, practice, and feedback are present, and effect sizes depend heavily on which evaluation criterion is used.",
    mechanism: "Training that targets an assessed need and provides practice with feedback changes capability; the criterion chosen determines what the reported effect even means.",
    traditions: ["instructional-design", "behavioral"], domains: ["professional-workplace", "health"], stages: ["adult-workplace"],
    functions: ["practice", "assess", "feedback"], grain: "program-system", maturity: "established",
    tasks: ["corporate and clinical training", "programme evaluation"],
    contexts: ["workplace learning", "professional development"],
    prereq: ["A documented needs assessment", "Practice with feedback in the design", "Criterion chosen before evaluation"],
    constraints: ["Reaction-level measures do not predict learning or behaviour", "Effect sizes differ substantially across criteria", "Self-report criteria inflate results"],
    risks: ["Smile sheets used as effectiveness evidence", "Skipping needs assessment and training the wrong thing", "Comparing effect sizes across different criteria"],
    obs: [["Criterion-specified outcomes", "Pre-specified learning, behaviour, and results measures, reported separately", "At each evaluation level", "Reaction data is not an outcome"]],
    ev: { status: "strong", confidence: "high", basis: "Meta-analysis of organizational training effectiveness showing meaningful effects that vary by evaluation criterion and by the presence of needs assessment, practice, and feedback.", directness: "direct-intervention", generalizability: "Organizational and professional training.", sources: ["arthur-training-meta", "blume-transfer-meta"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Declare the criterion before evaluating and never report reaction data as effectiveness." },
    tags: ["principle", "adult", "workplace", "measurement"],
  }),
  e({
    id: "simulation-based-mastery-learning", label: "Simulation-based mastery learning in clinical skills", layer: "method",
    aliases: ["deliberate practice with simulation", "mastery criterion clinical training"],
    summary: "Simulation training with a mastery criterion, deliberate practice, and feedback produces large skill gains and, in several studies, better patient outcomes.",
    mechanism: "Repeated practice against an explicit performance standard with immediate feedback continues until the standard is met, removing the variability of time-based training.",
    traditions: ["behavioral", "instructional-design"], domains: ["health", "professional-workplace"], stages: ["postsecondary", "adult-workplace"],
    functions: ["practice", "feedback", "assess"], grain: "program-system", maturity: "established",
    tasks: ["procedural skill training", "clinical competence", "certification"],
    contexts: ["clinical simulation", "professional education"],
    prereq: ["A validated performance checklist and mastery standard", "Simulation fidelity adequate to the skill", "Unlimited practice time to reach the standard"],
    constraints: ["Requires substantial faculty and equipment resources", "Checklist validity determines what mastery means", "Fidelity needs vary by skill; higher is not always better"],
    risks: ["Checklist compliance substituting for clinical judgment", "Declaring mastery on a weak standard", "Assuming simulation performance transfers without patient-level evidence"],
    obs: [["Mastery attainment and downstream transfer", "Checklist performance to criterion plus workplace or patient outcome measures", "At certification and after", "Simulation competence is not automatically clinical competence"]],
    ev: { status: "strong", confidence: "high", basis: "Meta-analyses of simulation-based mastery learning and of technology-enhanced simulation report large skill effects and, in a subset, patient-outcome benefits.", directness: "direct-intervention", generalizability: "Health professions education; strongest for procedural skills.", effect: { metric: "d", note: "Large effects on skills outcomes; smaller and less consistent for patient outcomes." }, sources: ["mcgaghie-simulation", "cook-simulation-jama", "kulik-mastery"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "The strongest adult-domain instance of mastery learning; require a validated standard and workplace-level follow-up." },
    tags: ["method", "health", "adult", "assessment"],
  }),
  e({
    id: "instructional-coaching", label: "Instructional coaching for practitioners", layer: "method",
    aliases: ["teacher coaching", "job-embedded professional development"],
    summary: "Individualized, sustained coaching improves practice and, more modestly, learner outcomes; effects shrink substantially as programmes scale.",
    mechanism: "Observation plus individualized feedback on real practice closes the gap that workshop-based training leaves between knowing and doing.",
    traditions: ["instructional-design", "sociocultural"], domains: ["teacher-development", "professional-workplace"], stages: ["adult-workplace"],
    functions: ["feedback", "practice", "transfer"], grain: "program-system", maturity: "established",
    tasks: ["practice improvement", "professional development", "implementation support"],
    contexts: ["schools", "workplace learning", "professional development"],
    prereq: ["Trained coaches with subject expertise", "Regular observation cycles", "Protected time and trust"],
    constraints: ["Effects on learner outcomes are much smaller than on practice", "Larger programmes show markedly smaller effects", "Coach quality is the binding constraint at scale"],
    risks: ["Scaling and expecting pilot-sized effects", "Coaching used as evaluation, which destroys trust", "One-off workshops labelled as coaching"],
    obs: [["Practice change and learner outcomes, separately", "Observation-rubric change plus independent learner achievement, with programme size reported", "Across a year", "Effects at pilot scale do not survive scaling"]],
    ev: { status: "strong", confidence: "high", basis: "Meta-analysis of teacher coaching finds large effects on instructional practice and smaller effects on achievement, with a clear scale-down pattern.", directness: "direct-intervention", generalizability: "Teacher development; the scaling caution is well documented.", effect: { metric: "d", value: 0.49, note: "Effect on instructional practice; about 0.18 on student achievement, and smaller in larger programmes." }, sources: ["kraft-coaching", "aero"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Best-evidenced professional learning model; plan explicitly for the effect decay that comes with scale." },
    tags: ["method", "teacher-development", "feedback", "adult"],
  }),
  e({
    id: "deliberate-practice-theory", label: "Deliberate practice theory of expertise", layer: "theory",
    aliases: ["Ericsson's deliberate practice", "expert performance framework"],
    summary: "Expert performance is claimed to arise from extended, effortful, feedback-rich practice designed to improve specific weaknesses rather than from experience alone.",
    mechanism: "Practice aimed at a specific deficiency, with immediate feedback and repetition, refines representations that ordinary experience leaves unchanged.",
    traditions: ["cognitive", "behavioral"], domains: ["music", "physical-motor", "professional-workplace", "general"], stages: ["primary", "middle", "secondary", "postsecondary", "adult-workplace"],
    functions: ["practice", "feedback"], grain: "program-system", maturity: "disputed",
    tasks: ["skill development", "expertise programmes", "coaching design"],
    contexts: ["music practice", "sports coaching", "professional education"],
    prereq: ["A coach or standard defining the specific deficiency", "Immediate informative feedback", "Sustained effortful repetition"],
    constraints: ["Accumulated practice explains a minority of performance variance across domains", "The strict definition is rarely met by what is labelled deliberate practice", "Domains with stable structure fit far better than ill-structured ones"],
    risks: ["Attributing failure to insufficient practice hours", "Meritocratic misuse to dismiss access and opportunity", "Labelling ordinary repetition as deliberate practice"],
    obs: [["Practice quality against the definition", "Records of targeted deficiency, feedback received, and performance change, not hours logged", "Across a training programme", "Hours accumulated is the weakest possible measure"]],
    ev: { status: "contested", confidence: "high", basis: "The original framework is influential, but meta-analysis shows accumulated deliberate practice accounts for a modest share of performance variance and varies sharply by domain.", directness: "mixed-direct-and-inferential", generalizability: "Best fit in music, chess, and sports; weak in ill-structured professions.", effect: { metric: "R-squared", note: "Roughly 20-25% of variance in music and games, far less in education and professions." }, sources: ["ericsson-deliberate-practice", "deliberate-practice-meta"] },
    rec: { status: "do-not-generalize", rationale: "Use its design features (specific target, feedback, repetition) and reject the hours-explain-expertise claim." },
    tags: ["theory", "expertise", "practice", "contested"],
  }),
  e({
    id: "self-regulation-in-open-online-learning", label: "Self-regulation demands of open online learning", layer: "construct",
    aliases: ["MOOC completion", "online course persistence"],
    summary: "Open online courses show very low completion and serve already-advantaged learners disproportionately; success depends heavily on self-regulatory capability the format assumes.",
    mechanism: "Removing schedule, cohort, and accountability structures shifts the entire regulatory burden onto the learner, which favours those who already have those skills.",
    traditions: ["motivational-social", "instructional-design"], domains: ["digital-environments", "professional-workplace"], stages: ["postsecondary", "adult-workplace", "older-adult"],
    functions: ["self-regulate", "access"], grain: "program-system", maturity: "established",
    tasks: ["open course design", "workforce upskilling", "access planning"],
    contexts: ["online platforms", "workplace learning", "continuing education"],
    prereq: ["Explicit regulatory supports if broad access is the goal", "Realistic outcome definitions beyond completion"],
    constraints: ["Completion is a poor and often misleading metric", "Participation skews toward the already-educated", "Self-regulation interventions in these settings show mixed results"],
    risks: ["Claiming democratized access without checking who participates", "Reading non-completion as learner failure", "Designing for the self-regulated minority"],
    obs: [["Who participates and what they achieve", "Participation and achievement disaggregated by prior education, plus goal-relative rather than completion-relative outcomes", "Across cohorts", "Completion rate conflates intent with capability"]],
    ev: { status: "strong", confidence: "high", basis: "Large-scale platform analyses show persistent low completion and advantaged participation; experimental self-regulation supports show modest and mixed effects.", directness: "mixed-direct-and-inferential", generalizability: "Open online platforms; less applicable to supported cohort programmes.", sources: ["reich-mooc", "kizilcec-mooc-srl", "bernard-distance"] },
    rec: { status: "contextual-option", rationale: "Build regulatory structure into the design and report participation equity, not just completion." },
    tags: ["construct", "digital", "adult", "equity"],
  }),
  e({
    id: "cognitive-aging-and-learning", label: "Cognitive aging and learning in later life", layer: "construct",
    aliases: ["fluid and crystallized ability", "older adult learning"],
    summary: "Processing speed and fluid reasoning decline with age while knowledge-based ability is preserved or grows, so older adults learn well with pacing, support, and knowledge-linked material.",
    mechanism: "Age-related slowing and working-memory reduction raise the cost of novel unstructured material, while preserved crystallized knowledge provides scaffolding when material connects to it.",
    traditions: ["developmental", "cognitive"], domains: ["general", "health", "professional-workplace"], stages: ["older-adult", "adult-workplace"],
    functions: ["access", "sequence", "practice"], grain: "unit-course", maturity: "established",
    tasks: ["later-life learning", "workforce retraining", "health education"],
    contexts: ["continuing education", "workplace learning", "clinical education"],
    prereq: ["Pacing under the learner's control", "Material linked to existing knowledge", "Sensory and interface accessibility"],
    constraints: ["Between-person variability increases with age; averages mislead badly", "Cross-sectional estimates overstate decline", "Engagement effects on cognition are not proven causal"],
    risks: ["Age-based assumptions about individual capability", "Fast-paced unmodifiable interfaces", "Selling cognitive-decline prevention claims"],
    obs: [["Learning under self-paced supported conditions", "Same content under learner-controlled versus fixed pacing plus knowledge-linked framing", "Across sessions", "A fixed-pace result underestimates what the learner can do"]],
    ev: { status: "strong", confidence: "high", basis: "Extensive lifespan cognition research on differential trajectories of fluid and crystallized abilities, with reviews of enrichment effects noting weaker causal evidence.", directness: "mixed-direct-and-inferential", generalizability: "Broad in cognitive aging research; individual variability is very large.", sources: ["salthouse-aging", "hertzog-enrichment", "hpl2"] },
    rec: { status: "candidate-default-with-fit-check", rationale: "Give pacing control and knowledge links; never infer an individual's capability from age." },
    tags: ["construct", "lifespan", "adult", "accessibility"],
  }),
  e({
    id: "adult-competency-frameworks", label: "Adult competency frameworks and population skill data", layer: "framework",
    aliases: ["PIAAC", "adult literacy and numeracy proficiency levels"],
    summary: "Large-scale adult competency assessments describe literacy, numeracy, and problem-solving proficiency across populations, and reveal that a substantial share of adults operate at low proficiency levels.",
    mechanism: "Standardized proficiency scales make population-level skill distributions comparable and expose the gap between assumed and actual adult capability.",
    traditions: ["psychometric"], domains: ["professional-workplace", "literacy", "mathematics"], stages: ["adult-workplace", "older-adult"],
    functions: ["assess", "diagnose", "access"], grain: "program-system", maturity: "established",
    tasks: ["programme targeting", "readability and design decisions", "policy analysis"],
    contexts: ["policy", "workplace learning", "product design"],
    prereq: ["Correct interpretation of proficiency levels", "Recognition that population data does not describe an individual"],
    constraints: ["Population-level data cannot classify an individual", "Proficiency levels are constructed cut points, not natural categories", "Country comparisons carry substantial methodological caveats"],
    risks: ["Designing adult materials for an assumed high proficiency", "Using population statistics to stereotype a group", "Reading proficiency levels as fixed capacity"],
    obs: [["Design against realistic proficiency distributions", "Usability and comprehension testing with the actual target population", "During design", "Designers systematically overestimate typical proficiency"]],
    ev: { status: "normative-standard", confidence: "high", basis: "A large international assessment programme providing standardized population proficiency data; descriptive rather than causal.", directness: "normative", generalizability: "Participating countries; population-level only.", sources: ["oecd-piaac", "testing-standards"] },
    rec: { status: "contextual-option", rationale: "Use to calibrate design assumptions about adult materials; never to characterize an individual learner." },
    tags: ["framework", "adult", "measurement", "access"],
  }),
];
