import { r } from "./lib.mjs";

// Relations added in 0.2.0. The 44 relations from 0.1.0 are inherited unchanged by the build.
const core = [
  // --- Prior knowledge and the fading of support -------------------------------------------
  r("expertise-reversal", "moderates", "worked-examples-fading", "conditional", "strong", "Worked examples help novices and become redundant or harmful as expertise grows.", ["kalyuga-expertise-reversal", "worked-examples-meta"]),
  r("expertise-reversal", "moderates", "contingent-scaffolding", "conditional", "strong", "Scaffolding that helps a novice interferes once the learner holds the schema.", ["kalyuga-expertise-reversal", "scaffolding-review"]),
  r("expertise-reversal", "moderates", "multimedia-learning-theory", "conditional", "strong", "Several multimedia principles reverse for high-prior-knowledge learners.", ["kalyuga-expertise-reversal", "mayer-multimedia-2017"]),
  r("expertise-reversal", "requires", "prior-knowledge-variable", "positive", "strong", "The reversal can only be managed if component-level prior knowledge is actually measured.", ["kalyuga-expertise-reversal", "kli-framework"]),
  r("prior-knowledge-variable", "moderates", "explicit-direct-instruction", "conditional", "strong", "Explicit guidance is most valuable for novices and should fade with knowledge.", ["kirschner-minimal-guidance", "rosenshine-principles"]),
  r("prior-knowledge-variable", "part-of", "knowledge-component-model", "positive", "context-dependent", "Component-level knowledge state is the variable the KLI framework models.", ["kli-framework"]),
  r("prior-knowledge-diagnostic", "precedes", "expertise-reversal", "positive", "strong", "Diagnosis supplies the knowledge estimate that fading decisions depend on.", ["hpl2", "kalyuga-expertise-reversal"]),

  // --- Desirable difficulties family -------------------------------------------------------
  r("desirable-difficulties", "supports", "retrieval-practice", "positive", "strong", "Retrieval is the canonical desirable difficulty: harder in session, better at delay.", ["bjork-self-regulated", "retrieval-meta", "rowland-testing-meta", "adesope-practice-testing", "agarwal-retrieval-classroom"]),
  r("desirable-difficulties", "supports", "spacing", "positive", "strong", "Spacing depresses practice fluency while improving retention.", ["bjork-self-regulated", "spacing-meta"]),
  r("desirable-difficulties", "supports", "interleaving-discrimination", "positive", "context-dependent", "Interleaving lowers practice performance and can raise discrimination at delay.", ["interleaving-meta", "soderstrom-bjork", "kornell-bjork-interleaving", "rohrer-taylor"]),
  r("desirable-difficulties", "supports", "contextual-interference", "positive", "strong", "Random practice ordering is the motor-domain instance of the same principle.", ["shea-morgan-contextual", "soderstrom-bjork"]),
  r("learning-vs-performance", "supports", "desirable-difficulties", "positive", "strong", "The distinction is what makes a difficulty legible as desirable rather than harmful.", ["soderstrom-bjork", "bjork-self-regulated"]),
  r("learning-vs-performance", "requires", "delayed-transfer-assessment", "positive", "strong", "Detecting the distinction requires deferred, support-free measurement.", ["soderstrom-bjork", "pan-rickard-transfer"]),
  r("delayed-transfer-assessment", "supports", "learning-vs-performance", "positive", "strong", "Delayed transfer measurement is how the distinction becomes operational.", ["soderstrom-bjork"]),

  // --- Cognitive architecture --------------------------------------------------------------
  r("cognitive-load-design", "implements", "cognitive-load-theory", "positive", "context-dependent", "The design principle operationalizes the theory's account of working memory limits.", ["sweller-1988", "cognitive-load"]),
  r("working-memory-capacity", "part-of", "cognitive-load-theory", "positive", "strong", "Capacity limits are the theory's central constraint.", ["sweller-1988", "cognitive-load"]),
  r("multimedia-coherence", "implements", "multimedia-learning-theory", "positive", "context-dependent", "Coherence is one of the theory's design principles.", ["mayer-multimedia-2017", "mayer-moreno-load"]),
  r("dual-coding", "supports", "multimedia-learning-theory", "positive", "context-dependent", "Dual coding supplies the two-channel assumption the theory builds on.", ["clark-paivio", "mayer-multimedia-2017"]),
  r("schema-knowledge-organization", "supports", "transfer-bridging", "positive", "strong", "Organized deep-structure knowledge is what makes transfer possible at all.", ["hpl1", "transfer-taxonomy"]),
  r("knowledge-component-model", "implements", "schema-knowledge-organization", "positive", "context-dependent", "Knowledge components are an operational decomposition of organized knowledge.", ["kli-framework"]),
  r("knowledge-component-model", "supports", "intelligent-tutoring-systems", "positive", "strong", "Step-level tutoring depends on a component-level learner model.", ["kli-framework", "vanlehn-tutoring"]),
  r("sociocultural-zpd", "supports", "contingent-scaffolding", "positive", "context-dependent", "Scaffolding is the instructional operationalization of the zone.", ["scaffolding-review", "hpl2"]),
  r("conceptual-change", "requires", "prior-knowledge-diagnostic", "positive", "context-dependent", "Existing conceptions must be elicited before they can be engaged.", ["posner-conceptual-change", "smith-misconceptions"]),
  r("attention-and-media-multitasking", "moderates", "cognitive-load-design", "negative", "context-dependent", "Divided attention adds load that no material-level design can remove.", ["ophir-multitasking", "cognitive-load"]),

  // --- Generation, error, and retrieval ----------------------------------------------------
  r("generation-effect", "supports", "retrieval-practice", "positive", "strong", "Retrieval practice is a generation manipulation applied to studied material.", ["slamecka-generation", "retrieval-meta", "roediger-karpicke"]),
  r("pretesting", "implements", "generation-effect", "positive", "context-dependent", "Pretesting applies generation before rather than after instruction.", ["richland-pretesting", "metcalfe-errors"]),
  r("errorful-learning", "requires", "actionable-feedback", "positive", "strong", "Errors help only when the correction actually arrives.", ["metcalfe-errors", "feedback-meta"]),
  r("errorful-learning", "supports", "pretesting", "positive", "context-dependent", "The pretesting benefit is a case of errorful generation followed by correction.", ["metcalfe-errors", "richland-pretesting"]),
  r("spaced-repetition-scheduling", "implements", "spacing", "positive", "strong", "Scheduling algorithms operationalize the spacing effect for large item sets.", ["spacing-meta", "kerfoot-spaced-education"]),
  r("test-enhanced-transfer-limits", "moderates", "retrieval-practice", "conditional", "strong", "Retrieval benefits retention far more reliably than transfer.", ["pan-rickard-transfer", "retrieval-meta"]),
  r("elaborative-interrogation", "complements", "self-explanation", "positive", "context-dependent", "Both prompt generated explanation; self-explanation targets the learner's own reasoning.", ["dunlosky-techniques", "chi-self-explanation"]),
  r("concept-mapping", "contrasts-with", "retrieval-practice", "conditional", "context-dependent", "Direct comparison favoured retrieval practice over concept mapping for retention.", ["karpicke-blunt", "nesbit-concept-mapping"]),
  r("analogical-case-comparison", "supports", "transfer-bridging", "positive", "strong", "Explicit comparison is one of the few reliable levers on transfer.", ["gentner-analogical", "transfer-taxonomy"]),
  r("variation-theory", "complements", "analogical-case-comparison", "positive", "hypothesis", "Both concern what must vary across examples for a critical feature to be discerned.", ["kullberg-variation", "gentner-analogical"]),
  r("contrasting-cases-invention", "implements", "productive-failure", "positive", "context-dependent", "Invention before instruction is the canonical productive-failure design.", ["schwartz-martin-invention", "productive-failure-meta"]),
  r("contrasting-cases-invention", "precedes", "explicit-direct-instruction", "positive", "context-dependent", "The generation phase is only productive when consolidation follows it.", ["productive-failure-meta", "schwartz-martin-invention"]),

  // --- Method relations --------------------------------------------------------------------
  r("explicit-direct-instruction", "implements", "cognitive-load-theory", "positive", "context-dependent", "Small steps and checking manage working-memory demand during acquisition.", ["rosenshine-principles", "cognitive-load"]),
  r("explicit-direct-instruction", "requires", "checking-for-understanding", "positive", "strong", "Without frequent checking it degenerates into uninterrupted presentation.", ["rosenshine-principles", "wiliam-assessment"]),
  r("explicit-direct-instruction", "should-fade-into", "guided-inquiry", "conditional", "strong", "As knowledge grows, guidance should decrease toward more open investigation.", ["kalyuga-expertise-reversal", "alfieri-discovery"]),
  r("minimal-guidance-instruction", "contrasts-with", "guided-inquiry", "negative", "strong", "Guided discovery outperforms both explicit instruction and unassisted discovery.", ["alfieri-discovery", "kirschner-minimal-guidance"]),
  r("guided-inquiry", "requires", "contingent-scaffolding", "positive", "strong", "Guidance level is the active ingredient in inquiry effectiveness.", ["lazonder-harmsen", "alfieri-discovery"]),
  r("problem-based-learning", "requires", "prior-knowledge-variable", "positive", "contested", "Learners need enough prior knowledge to engage the problem productively.", ["kirschner-minimal-guidance", "dochy-pbl-meta"]),
  r("problem-based-learning", "contrasts-with", "explicit-direct-instruction", "conditional", "contested", "The two favour different outcome types: application versus knowledge coverage.", ["dochy-pbl-meta", "kirschner-minimal-guidance"]),
  r("project-based-learning", "requires", "explicit-direct-instruction", "positive", "context-dependent", "Projects need embedded instruction on the knowledge they use.", ["chen-pbl-meta", "kirschner-minimal-guidance"]),
  r("mastery-learning", "implements", "formative-assessment-cycle", "positive", "context-dependent", "Mastery learning is a formative cycle with a fixed criterion and variable time.", ["kulik-mastery", "formative-review"]),
  r("mastery-learning", "requires", "curriculum-based-measurement", "positive", "context-dependent", "A mastery criterion needs repeatable equivalent measurement to be meaningful.", ["deno-cbm", "kulik-mastery"]),
  r("simulation-based-mastery-learning", "implements", "mastery-learning", "positive", "strong", "Clinical simulation mastery training is mastery learning in a professional domain.", ["mcgaghie-simulation", "kulik-mastery"]),
  r("intelligent-tutoring-systems", "complements", "one-to-one-tutoring", "positive", "strong", "Step-based tutoring systems approach human tutoring effectiveness.", ["vanlehn-tutoring", "kulik-fletcher-its"]),
  r("peer-tutoring", "complements", "one-to-one-tutoring", "positive", "strong", "Peer tutoring extends tutoring benefits at lower marginal cost with more structure required.", ["cohen-tutoring-meta", "johnson-cooperative"]),
  r("cooperative-structures", "implements", "structured-collaboration", "positive", "strong", "Interdependence plus individual accountability is what makes collaboration work.", ["johnson-cooperative", "roseth-cooperative"]),
  r("reciprocal-teaching", "implements", "cooperative-structures", "positive", "strong", "Role transfer through structured dialogue is a cooperative comprehension design.", ["palincsar-brown", "rosenshine-reciprocal"]),
  r("reciprocal-teaching", "requires", "literacy-phoneme-grapheme", "positive", "strong", "Comprehension dialogue presumes the learner can decode the text.", ["hoover-gough-svr", "reading-comprehension-wwc"]),
  r("active-learning-stem", "implements", "icap-engagement-hypothesis", "positive", "context-dependent", "Active learning designs vary in how far up the ICAP ordering they reach.", ["freeman-active-learning", "icap", "chi-overt-activities"]),
  r("active-learning-stem", "requires", "checking-for-understanding", "positive", "strong", "The benefit comes from eliciting and responding to every learner's current state.", ["freeman-active-learning", "wiliam-assessment"]),
  r("flipped-classroom", "requires", "active-learning-stem", "positive", "context-dependent", "The gain comes from what replaces lecture in class, not from the video.", ["vanalten-flipped", "freeman-active-learning"]),
  r("blended-online-learning", "moderates", "flipped-classroom", "conditional", "context-dependent", "Delivery mode shapes access and interaction but does not itself produce learning.", ["bernard-distance", "vanalten-flipped"]),
  r("self-regulation-in-open-online-learning", "moderates", "blended-online-learning", "negative", "strong", "Removing structure shifts the regulatory burden onto the learner and filters who succeeds.", ["reich-mooc", "kizilcec-mooc-srl"]),
  r("simulations-virtual-labs", "implements", "guided-inquiry", "positive", "context-dependent", "Simulations work when the investigation is guided and debriefed.", ["dejong-simulations", "lazonder-harmsen"]),
  r("game-based-learning", "contrasts-with", "gamification-reward-layers", "conditional", "context-dependent", "Instructional games embed learning in the mechanics; gamification adds rewards around an unchanged activity.", ["wouters-serious-games", "sailer-gamification"]),
  r("gamification-reward-layers", "does-not-imply", "motivation-need-support", "conditional", "context-dependent", "Points and leaderboards can undermine autonomy while raising short-term activity.", ["sailer-gamification", "ryan-deci-sdt"]),
  r("homework-practice", "implements", "spacing", "positive", "context-dependent", "Out-of-class practice is only justified as distributed retrieval, not as new instruction.", ["cooper-homework", "spacing-meta"]),
  r("differentiated-instruction", "requires", "prior-knowledge-variable", "positive", "context-dependent", "Differentiation must route on current task evidence rather than on labels.", ["deunk-differentiation", "kli-framework"]),
  r("differentiated-instruction", "does-not-imply", "learning-styles-matching", "negative", "refuted", "Adapting on assessed performance is not adapting on a supposed style.", ["learning-styles", "willingham-learning-styles"]),
  r("study-skills-programs", "requires", "transfer-bridging", "positive", "strong", "Detached strategy courses fail precisely because conditions of use are not taught.", ["hattie-study-skills", "transfer-taxonomy"]),

  // --- Motivation ---------------------------------------------------------------------------
  r("motivation-need-support", "implements", "self-determination-theory", "positive", "strong", "Need-supportive design is the theory's applied form.", ["ryan-deci-sdt", "motivation-meta"]),
  r("expectancy-value-theory", "complements", "self-determination-theory", "positive", "strong", "Expectancy and value explain choice; needs explain the quality of the motivation.", ["eccles-wigfield-2020", "ryan-deci-sdt"]),
  r("utility-value-intervention", "implements", "expectancy-value-theory", "positive", "context-dependent", "The intervention manipulates the value term directly.", ["hulleman-utility-value", "eccles-wigfield-2020"]),
  r("self-efficacy", "part-of", "expectancy-value-theory", "positive", "strong", "Task-specific efficacy is the expectancy component in operational form.", ["bandura-self-efficacy", "eccles-wigfield-2020"]),
  r("achievement-goal-orientation", "complements", "expectancy-value-theory", "positive", "context-dependent", "Goal orientation describes what success means; expectancy-value describes whether it is pursued.", ["elliot-mcgregor", "eccles-wigfield-2020"]),
  r("interest-development", "complements", "expectancy-value-theory", "positive", "context-dependent", "Interest is one durable source of the value term.", ["hidi-renninger", "eccles-wigfield-2020"]),
  r("belonging-intervention", "complements", "classroom-climate", "conditional", "contested", "Belonging messages depend on an environment that can actually support belonging.", ["walton-cohen-belonging", "wang-degol-climate"]),
  r("grit-construct", "complements", "growth-mindset-warning", "conditional", "contested", "Both are popular trait-level constructs whose achievement claims exceed their evidence.", ["crede-grit-meta", "growth-mindset-meta", "sisk-mindset-meta"]),
  r("stereotype-threat", "moderates", "assessment-fair-access", "conditional", "contested", "Identity-relevant framing is one of several construct-irrelevant threats in assessment.", ["flore-stereotype-meta", "testing-standards"]),
  r("teacher-expectancy", "moderates", "differentiated-instruction", "negative", "context-dependent", "Differentiation can encode low expectations as reduced curriculum access.", ["jussim-harber", "steenbergen-grouping"]),
  r("math-and-test-anxiety", "moderates", "fact-fluency", "negative", "strong", "Timed public fluency formats are a documented source of mathematics anxiety.", ["barroso-math-anxiety", "ashcraft-krause"]),
  r("math-and-test-anxiety", "moderates", "prior-knowledge-diagnostic", "negative", "strong", "Anxious underperformance can be misread as a knowledge gap.", ["ashcraft-krause", "barroso-math-anxiety"]),
  r("engagement-construct", "does-not-imply", "icap-engagement-hypothesis", "conditional", "context-dependent", "Behavioural engagement is not the cognitive engagement ICAP orders.", ["fredricks-engagement", "icap"]),
  r("classroom-management", "supports", "classroom-climate", "positive", "strong", "Proactive relational management is a main lever on classroom climate.", ["korpershoek-classroom-management", "roorda-relationships"]),
  r("social-emotional-learning", "supports", "classroom-climate", "positive", "strong", "SEL programmes act partly through improved climate and relationships.", ["durlak-sel", "wang-degol-climate"]),
  r("socioeconomic-context", "moderates", "one-to-one-tutoring", "conditional", "strong", "Intensive support shows the largest gains where opportunity has been most constrained.", ["dietrichson-low-ses", "cohen-tutoring-meta"]),
  r("metacognitive-monitoring-accuracy", "part-of", "metacognitive-calibration", "positive", "strong", "Monitoring accuracy is the measurable core of calibration.", ["dunlosky-rawson-overconfidence", "bjork-self-regulated"]),
  r("metacognitive-monitoring-accuracy", "requires", "delayed-transfer-assessment", "positive", "strong", "Calibration can only be computed against an external delayed performance measure.", ["dunlosky-rawson-overconfidence", "soderstrom-bjork"]),
  r("goal-setting-and-implementation-intentions", "moderates", "study-skills-programs", "positive", "strong", "Specific goals plus if-then plans convert strategy knowledge into strategy use.", ["locke-latham-goals", "hattie-study-skills"]),

  // --- Feedback -------------------------------------------------------------------------------
  r("feedback-design-levels", "implements", "actionable-feedback", "positive", "strong", "The four-level account specifies which feedback focus is usable.", ["hattie-timperley-feedback", "feedback-meta"]),
  r("feedback-literacy", "requires", "feedback-design-levels", "positive", "context-dependent", "Uptake capability presumes the feedback carries gap-closing information.", ["carless-feedback-literacy", "hattie-timperley-feedback"]),
  r("reduced-feedback-frequency", "moderates", "actionable-feedback", "conditional", "strong", "Constant feedback improves performance while present and can impair learning.", ["winstein-schmidt", "soderstrom-bjork"]),
  r("reduced-feedback-frequency", "implements", "learning-vs-performance", "positive", "strong", "The guidance effect is a clean instance of the performance-learning dissociation.", ["winstein-schmidt", "soderstrom-bjork"]),
  r("l2-corrective-feedback", "implements", "feedback-design-levels", "positive", "strong", "Explicitness and timing choices in language feedback follow the general feedback account.", ["li-corrective-feedback", "hattie-timperley-feedback"]),
  r("instructional-coaching", "implements", "feedback-design-levels", "positive", "strong", "Coaching is observation-based process feedback with a revision opportunity.", ["kraft-coaching", "hattie-timperley-feedback"]),

  // --- Early childhood ------------------------------------------------------------------------
  r("executive-function-development", "supports", "early-intentional-practice", "positive", "strong", "Executive function is one of the target domains of intentional early practice.", ["diamond-executive-function", "early-childhood-wwc"]),
  r("executive-function-curricula", "implements", "executive-function-development", "conditional", "contested", "Curricula attempt to operationalize EF development with inconsistent results.", ["blair-raver-tools", "diamond-ling"]),
  r("executive-function-curricula", "does-not-imply", "transfer-bridging", "negative", "contested", "EF gains do not reliably transfer to academic outcomes.", ["diamond-ling", "melby-lervag-wm-training"]),
  r("dialogic-shared-reading", "implements", "responsive-language-interaction", "positive", "strong", "Dialogic reading is a structured form of responsive adult-child language interaction.", ["whitehurst-dialogic", "mol-dialogic-meta"]),
  r("dialogic-shared-reading", "supports", "early-vocabulary-instruction", "positive", "strong", "Shared reading supplies meaningful contexts for taught words.", ["mol-dialogic-meta", "marulis-vocabulary"]),
  r("home-learning-environment", "complements", "dialogic-shared-reading", "positive", "context-dependent", "Home shared reading is the main site where dialogic reading occurs.", ["senechal-lefevre", "mol-dialogic-meta"]),
  r("guided-play", "part-of", "playful-learning-continuum", "positive", "context-dependent", "Guided play is the segment of the continuum with the clearest learning evidence.", ["weisberg-guided-play", "guided-play-review"]),
  r("montessori-education", "implements", "playful-learning-continuum", "conditional", "context-dependent", "Montessori occupies a specific position on the agency-and-structure continuum.", ["lillard-montessori", "weisberg-guided-play"]),
  r("early-number-magnitude", "supports", "early-math-progression", "positive", "strong", "Magnitude representation is an early anchor point in mathematical progressions.", ["siegler-ramani-games", "early-math-nrc"]),
  r("learning-trajectories", "implements", "early-math-progression", "positive", "context-dependent", "Trajectories are the operational form of developmental progressions.", ["clements-trajectories", "early-math-wwc"]),
  r("spatial-skills-training", "complements", "early-number-magnitude", "positive", "context-dependent", "Spatial and magnitude representations are related early mathematical foundations.", ["uttal-spatial-training", "early-math-nrc"]),
  r("early-vocabulary-instruction", "supports", "reading-comprehension-knowledge", "positive", "strong", "Vocabulary depth is a component of later comprehension.", ["marulis-vocabulary", "reading-comprehension-wwc"]),
  r("preschool-effects-and-convergence", "moderates", "early-intentional-practice", "conditional", "contested", "Short-term early gains often converge unless subsequent grades sustain them.", ["durkin-tnvpk", "heckman-perry"]),
  r("screen-media-young-children", "moderates", "responsive-language-interaction", "negative", "context-dependent", "Screen use matters mainly through what interaction it displaces.", ["madigan-screen-time", "hpl2"]),
  r("sleep-and-consolidation", "moderates", "spacing", "positive", "strong", "Sleep between spaced sessions is part of what consolidates the learning.", ["diekelmann-born-sleep", "spacing-meta"]),
  r("physical-activity-and-cognition", "complements", "executive-function-development", "positive", "context-dependent", "Activity is one of the supports associated with executive function development.", ["donnelly-physical-activity", "diamond-ling"]),
  r("early-science-engineering", "precedes", "science-three-dimensional", "positive", "context-dependent", "Early investigation practices lay groundwork for three-dimensional science learning.", ["preschool-science-nasem", "science-framework"]),

  // --- Literacy and language --------------------------------------------------------------------
  r("simple-view-of-reading", "supports", "literacy-phoneme-grapheme", "positive", "strong", "The decoding component is what code instruction targets.", ["hoover-gough-svr", "castles-reading-wars"]),
  r("systematic-phonics-programme", "implements", "literacy-phoneme-grapheme", "positive", "strong", "A systematic programme is the planned delivery of phoneme-grapheme mapping.", ["ehri-phonics-meta", "literacy-wwc"]),
  r("systematic-phonics-programme", "does-not-imply", "reading-comprehension-knowledge", "conditional", "strong", "Word-reading gains are much larger than comprehension gains.", ["ehri-phonics-meta", "castles-reading-wars"]),
  r("reading-fluency-repeated-reading", "requires", "systematic-phonics-programme", "positive", "strong", "Fluency practice presumes the decoding skill it automates.", ["therrien-repeated-reading", "nrp"]),
  r("knowledge-and-comprehension", "supports", "reading-comprehension-knowledge", "positive", "strong", "Topic knowledge is a primary driver of what a reader understands.", ["recht-leslie", "reading-comprehension-wwc"]),
  r("text-structure-instruction", "implements", "reading-comprehension-knowledge", "positive", "strong", "Structure instruction is one evidence-rated comprehension practice.", ["reading-comprehension-wwc", "adolescent-literacy-wwc"]),
  r("disciplinary-literacy", "requires", "knowledge-and-comprehension", "positive", "context-dependent", "Disciplinary reading presumes the background knowledge to contextualize sources.", ["shanahan-disciplinary", "recht-leslie"]),
  r("historical-thinking-sourcing", "implements", "disciplinary-literacy", "positive", "context-dependent", "Sourcing and corroboration are the history-specific instance.", ["wineburg-historical", "shanahan-disciplinary"]),
  r("writing-strategy-instruction", "implements", "writing-model-practice-reflect", "positive", "strong", "Strategy instruction is the highest-effect form of the model-practice-reflect cycle.", ["graham-elementary-writing", "writing-wwc"]),
  r("adolescent-reading-intervention", "requires", "simple-view-of-reading", "positive", "strong", "Older struggling readers must be routed by component profile, not by age.", ["reading-intervention-wwc", "hoover-gough-svr"]),
  r("instructed-second-language-acquisition", "supports", "academic-language-multilingual", "positive", "strong", "Explicit attention to language form supports academic language development.", ["norris-ortega", "ell-wwc"]),
  r("task-based-language-teaching", "complements", "instructed-second-language-acquisition", "conditional", "context-dependent", "Tasks supply the meaningful use that explicit form focus needs to attach to.", ["bryfonski-tblt", "norris-ortega"]),
  r("multilingual-programme-models", "supports", "academic-language-multilingual", "positive", "strong", "Programme design determines whether content and language develop together.", ["english-learners-nasem", "ell-wwc"]),

  // --- Subject domains ------------------------------------------------------------------------
  r("conceptual-procedural-iteration", "moderates", "fact-fluency", "conditional", "strong", "Fluency without conceptual anchoring produces brittle, unadaptable performance.", ["rittle-johnson-iterative", "adding-it-up"]),
  r("mathematical-proficiency-strands", "complements", "conceptual-procedural-iteration", "positive", "normative-standard", "The strands framework names what the iterative account describes developmentally.", ["adding-it-up", "rittle-johnson-iterative"]),
  r("schema-based-word-problems", "implements", "math-systematic-representations", "positive", "strong", "Schema diagrams are systematic representations tied to quantity.", ["jitendra-schema", "math-intervention-wwc"]),
  r("fact-fluency", "supports", "schema-based-word-problems", "positive", "context-dependent", "Automatic facts free capacity for the structural reasoning a word problem needs.", ["math-intervention-wwc", "cognitive-load"]),
  r("algebra-instruction-strategies", "implements", "worked-examples-fading", "positive", "strong", "Solved-problem analysis is worked-example instruction in algebra.", ["algebra-wwc", "worked-examples-meta"]),
  r("algebra-instruction-strategies", "complements", "math-strategy-comparison", "positive", "context-dependent", "Strategy comparison is one of the algebra guide's recommended practices.", ["algebra-wwc", "rittle-johnson-star-comparison"]),
  r("science-argumentation", "implements", "science-three-dimensional", "positive", "context-dependent", "Argumentation is one of the framework's core science practices.", ["osborne-argumentation", "science-framework"]),
  r("conceptual-change", "supports", "science-argumentation", "positive", "context-dependent", "Argument from evidence is a main mechanism by which conceptions are revised.", ["osborne-argumentation", "posner-conceptual-change"]),
  r("pair-programming", "implements", "cooperative-structures", "positive", "context-dependent", "Driver-navigator roles are a computing-specific interdependence structure.", ["hannay-pair-programming", "johnson-cooperative"]),
  r("computational-thinking-transfer", "moderates", "computing-practices", "conditional", "context-dependent", "Transfer claims for computing practices decline sharply with distance.", ["scherer-computational-thinking", "transfer-taxonomy"]),
  r("contextual-interference", "implements", "desirable-difficulties", "positive", "strong", "Random ordering is the motor-learning form of a desirable difficulty.", ["shea-morgan-contextual", "bjork-self-regulated"]),
  r("contextual-interference", "complements", "interleaving-discrimination", "positive", "strong", "The two are the motor and cognitive expressions of the same manipulation.", ["shea-morgan-contextual", "interleaving-meta"]),
  r("external-attentional-focus", "complements", "contextual-interference", "positive", "context-dependent", "Both are practice-design variables in motor skill acquisition.", ["wulf-attentional-focus", "shea-morgan-contextual"]),

  // --- Adult and workplace ----------------------------------------------------------------------
  r("andragogy", "does-not-imply", "adult-self-directed-learning", "conditional", "contested", "Adult status does not confer self-direction in an unfamiliar domain.", ["merriam-adult-theory", "kirschner-urban-legends"]),
  r("transformative-learning", "complements", "andragogy", "positive", "hypothesis", "Both are adult-education frameworks with design value and weak causal evidence.", ["mezirow-transformative", "merriam-adult-theory"]),
  r("transfer-of-training", "implements", "transfer-bridging", "positive", "strong", "Workplace transfer is the organizational instance of the transfer problem.", ["baldwin-ford", "transfer-taxonomy"]),
  r("training-design-effectiveness", "requires", "transfer-of-training", "positive", "strong", "Design quality is insufficient without a supportive transfer environment.", ["arthur-training-meta", "blume-transfer-meta"]),
  r("simulation-based-mastery-learning", "implements", "deliberate-practice-theory", "positive", "context-dependent", "Clinical mastery training uses the deliberate-practice design features.", ["mcgaghie-simulation", "ericsson-deliberate-practice"]),
  r("deliberate-practice-theory", "contrasts-with", "deliberate-practice-bounds", "conditional", "contested", "The original framework's explanatory claim exceeds what meta-analysis supports.", ["ericsson-deliberate-practice", "deliberate-practice-meta"]),
  r("cognitive-aging-and-learning", "moderates", "spaced-repetition-scheduling", "conditional", "strong", "Pacing control matters more as processing speed declines.", ["salthouse-aging", "spacing-meta"]),
  r("adult-competency-frameworks", "moderates", "adult-self-directed-learning", "conditional", "normative-standard", "Population proficiency data constrains realistic assumptions about adult learners.", ["oecd-piaac", "merriam-adult-theory"]),
  r("instructional-coaching", "implements", "transfer-of-training", "positive", "strong", "Job-embedded coaching addresses the transfer environment directly.", ["kraft-coaching", "baldwin-ford"]),

  // --- Assessment --------------------------------------------------------------------------------
  r("formative-assessment-effect-caution", "moderates", "formative-assessment-cycle", "conditional", "contested", "Umbrella effect estimates are much smaller than commonly quoted.", ["kingston-nash-formative", "formative-critique"]),
  r("assessment-for-learning-strategies", "implements", "formative-assessment-cycle", "positive", "strong", "Strategy-level specification is what makes the cycle implementable and auditable.", ["wiliam-assessment", "formative-review"]),
  r("checking-for-understanding", "implements", "assessment-for-learning-strategies", "positive", "strong", "Eliciting evidence is one of the named strategies.", ["wiliam-assessment", "rosenshine-principles"]),
  r("peer-assessment", "implements", "assessment-for-learning-strategies", "positive", "strong", "Activating learners as resources for one another is one of the named strategies.", ["double-peer-assessment", "wiliam-assessment"]),
  r("self-assessment", "requires", "rubrics-and-exemplars", "positive", "strong", "Self-assessment without explicit criteria is unreliable.", ["panadero-self-assessment", "jonsson-rubrics"]),
  r("rubrics-and-exemplars", "supports", "peer-assessment", "positive", "strong", "Shared criteria are what make peer feedback specific enough to use.", ["jonsson-rubrics", "double-peer-assessment"]),
  r("curriculum-based-measurement", "supports", "multi-tiered-support", "positive", "strong", "Tiered routing depends on repeatable progress measurement.", ["deno-cbm", "fuchs-rti"]),
  r("multi-tiered-support", "requires", "explicit-direct-instruction", "positive", "context-dependent", "Without strong universal instruction the tiers become a referral pipeline.", ["fuchs-rti", "rosenshine-principles"]),
  r("assessment-validity-precision", "moderates", "curriculum-based-measurement", "conditional", "normative-standard", "Slope interpretation is a validity claim that needs adequate data density.", ["testing-standards", "deno-cbm"]),

  // --- Anti-patterns ------------------------------------------------------------------------------
  r("learning-styles-matching", "part-of", "neuromyths", "positive", "refuted", "Learning styles is the most prevalent educational neuromyth.", ["dekker-neuromyths", "learning-styles"]),
  r("multiple-intelligences-matching", "part-of", "neuromyths", "positive", "refuted", "Instructional matching by intelligence type shares the same refuted logic.", ["waterhouse-mi-critique", "dekker-neuromyths"]),
  r("brain-training-transfer", "contrasts-with", "working-memory-capacity", "negative", "refuted", "Capacity constrains learning, but training it does not transfer to academics.", ["melby-lervag-wm-training", "simons-brain-training"]),
  r("music-chess-far-transfer", "contrasts-with", "transfer-bridging", "negative", "refuted", "Far transfer without shared structure does not occur, however appealing the claim.", ["sala-gobet-music", "transfer-taxonomy"]),
  r("digital-natives-myth", "supports", "attention-and-media-multitasking", "positive", "refuted", "No group multitasks without switching cost, whatever their device familiarity.", ["kirschner-digital-native", "ophir-multitasking"]),
  r("rereading-and-highlighting", "contrasts-with", "retrieval-practice", "negative", "refuted", "The most common study strategies are among the least effective.", ["dunlosky-techniques", "retrieval-meta"]),
  r("rereading-and-highlighting", "supports", "metacognitive-monitoring-accuracy", "conditional", "strong", "Fluency-based strategies are the main driver of the overconfidence problem.", ["dunlosky-rawson-overconfidence", "dunlosky-techniques"]),
  r("learner-knows-best", "supports", "metacognitive-monitoring-accuracy", "positive", "strong", "Learner judgments of instruction are subject to the same fluency illusion.", ["deslauriers-feeling", "soderstrom-bjork"]),
  r("learner-knows-best", "contrasts-with", "engagement-construct", "conditional", "strong", "Satisfaction and engagement metrics can move opposite to learning.", ["deslauriers-feeling", "fredricks-engagement"]),
  r("minimal-guidance-instruction", "contrasts-with", "productive-failure", "conditional", "context-dependent", "A bounded generation phase with guaranteed consolidation is not minimal guidance.", ["productive-failure-meta", "kirschner-minimal-guidance"]),
];

// Added to connect entries that were otherwise unrelated in the graph.
const bridging = [
  r("threshold-concepts", "complements", "conceptual-change", "positive", "hypothesis", "Both describe reorganization of understanding rather than accumulation of facts.", ["meyer-threshold", "vosniadou-conceptual-change"]),
  r("blooms-revised-taxonomy", "complements", "assessment-triangle", "positive", "normative-standard", "Both are alignment frameworks: one classifies the objective, the other the inference chain.", ["krathwohl-taxonomy", "assessment-nrc"]),
  r("deeper-learning-competencies", "requires", "transfer-bridging", "positive", "context-dependent", "Transferable competence depends on domain learning plus explicit conditions of use.", ["education-life-work", "transfer-taxonomy"]),
  r("tpack", "complements", "blended-online-learning", "conditional", "context-dependent", "Tool choice is only defensible relative to content and pedagogical purpose.", ["mishra-tpack", "bernard-distance"]),
  r("learning-strategy-model", "moderates", "study-skills-programs", "conditional", "hypothesis", "Which strategy helps depends on the learner's current phase for that content.", ["hattie-donoghue-model", "hattie-study-skills"]),
  r("summarization-training", "contrasts-with", "retrieval-practice", "negative", "context-dependent", "Summarization is rated low utility relative to practice testing.", ["dunlosky-techniques", "retrieval-meta"]),
  r("note-taking", "complements", "summarization-training", "positive", "context-dependent", "Both depend on selection and paraphrase rather than verbatim capture.", ["mueller-oppenheimer", "dunlosky-techniques"]),
  r("wait-time", "supports", "checking-for-understanding", "positive", "context-dependent", "Extending think time changes who can answer the checking question.", ["rowe-wait-time", "rosenshine-principles"]),
  r("gesture-and-embodiment", "supports", "concrete-abstract-linking", "positive", "context-dependent", "Gesture externalizes the relational structure a concrete representation is meant to carry.", ["goldin-meadow-gesture", "hpl2", "fyfe-concreteness-fading"]),
];

const closing = [
  r("udl-options", "implements", "accessibility-by-design", "conditional", "normative-standard", "UDL operationalizes access as design options; conformance standards remain the floor beneath it.", ["udl-guidelines", "wcag22", "unesco-inclusion"]),
  r("system-resource-tradeoffs", "moderates", "one-to-one-tutoring", "conditional", "context-dependent", "Intensive tutoring competes for the same budget as structural levers with smaller effects.", ["eef-toolkit", "filges-class-size", "cohen-tutoring-meta"]),
  r("system-resource-tradeoffs", "moderates", "instructional-coaching", "conditional", "context-dependent", "Teacher effects are large enough that improving teaching is usually a better buy than structural change.", ["nye-teacher-effects", "kraft-coaching"]),
  r("system-resource-tradeoffs", "complements", "socioeconomic-context", "positive", "strong", "Resource decisions are where opportunity gaps are either narrowed or reproduced.", ["dietrichson-low-ses", "sirin-ses-meta"]),
];

export default [...core, ...bridging, ...closing];
